/**
 * wuwei.nls.CN.js
 * CN translation map
 *
 * Revised against JA baseline on 2026-04-17.
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 **/
wuwei.nls.CN = {
  'Publish': '发布',
  'Align': '对齐',
  'Define / Ungroup': '定义/取消分组',
  'Other': '其他',
  'Published': 'Published',
  'Public URL': 'Public URL',
  'Open in new tab': 'Open in new tab',
  'Copy URL': 'Copy URL',
  'Copied': 'Copied',
  'Published note is view-only. Editing, saving, and downloading are disabled.': 'Published note is view-only. Editing, saving, and downloading are disabled.',
  'Disabled': 'Disabled',
  'Download note file': 'Download note file',
  'Upload note file': 'Upload note file',
  'Imported note file': 'Imported note file',
  'Add Page': 'Add Page',
  'Select a page and edit its name.': 'Select a page and edit its name.',
  'Select a page to copy.': 'Select a page to copy.',
  'Select a page to open, edit, copy, or delete.': 'Select a page to open, edit, copy, or delete.',
  'WuWei Home': 'WuWei Home',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.',
  'Search content': 'Search content',
  'Calendar': 'Calendar',
  'Commands': 'Commands',
  'Comment to capture your viewpoint before opening a note.': 'Comment to capture your viewpoint before opening a note.',
  'Content gallery': 'Content gallery',
  'Add to note': 'Add to note',
  'Start date': 'Start date',
  'End date': 'End date',
  'Range target': 'Range target',
  'All content in range': 'All content in range',
  'Selected content in range': 'Selected content in range',
  'Search scope': 'Search scope',
  'Current period': 'Current period',
  'All registered content': 'All registered content',
  'Apply': 'Apply',
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': 'Create a new note from the selected content? Unsaved changes in the current note will be discarded.',
  'Selected content': 'Selected content',
  'Open note': 'Open note',
  'New note': 'New note',
  'No comment yet': 'No comment yet',
  'Click a card to preview the content and start working.': 'Click a card to preview the content and start working.',
  'No content in selected period': 'No content in selected period',
  'Upload content or choose another date from the calendar.': 'Upload content or choose another date from the calendar.',
  'Selected day': 'Selected day',
  'Month': 'Month',
  'Showing': 'Showing',
  'Date': '日期',
  'Type': '类型',
  'Title': 'Title',
  'Failed to save comment': 'Failed to save comment',
  'Format': 'Format',
  'Saved': 'Saved',
  'This site refused iframe preview.': 'This site refused iframe preview.',
  'Delete this timeline segment?': '删除此时间线区段？',
  'OpenPlayer': '在播放器中打开',
  'Create timeline axis': '创建时间轴',
  'Axis properties': '轴属性',
  'Add segment from player': '从播放器添加片段',
  'Segment properties': '片段属性',
  'Edit segment from player': '从播放器编辑片段',
  'Delete segment': '删除片段',
  'Info Timeline Segment': '时间轴信息',
  'SelectAll': '全选',
  'Show All Memo': '显示全部便笺',
  'Hide All Memo': '隐藏全部便笺',
  'Note Page': '页面信息',
  'Select shape': '选择形状',
  'Select font size': '选择字号',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'iframe 预览不会获取当前/播放位置，而是保存开始/结束时间，并使用 Open Player。',
  'Timeline axis': '时间轴',
  'Media': '媒体',
  'Direction': '方向',
  'horizontal': '水平',
  'vertical': '垂直',
  'Media length': '媒体长度',
  'Default play duration': '默认播放时长',
  'Axis length': '轴长度',
  'Axis width': '轴宽',
  'Axis color': '轴颜色',
  'Timeline segment': '时间轴区段',
  'Video preview': '视频预览',
  'Set current time to start': '设为开始时间',
  'Set current time to end': '设为结束时间',
  'Create thumbnail': '创建缩略图',
  'Start time': '开始时间',
  'End time': '结束时间',
  'or': '或',
  'Play duration': '播放时长',
  'info': '信息',
  'Background Color': '背景色',
  'Length': '长度',
  'Segments': '区段数',
  'Default': '默认',
  'End': '结束',
  'Image': '图像',
  'Video': '视频',
  'Audio': '音频',
  'Apply to group': '应用到组',
  'Media type': '媒体类型',
  'Timeline': '时间轴',
  'Document': '文档',
  'Duration': '时长',
  'Auto': '自动',
  'jump start': '跳到开始位置',
  'jump end': '跳到结束位置',
  'set start here': '将此处设为开始位置',
  'set end here': '将此处设为结束位置',
  'apply': '应用',
  'Define simple group': '定义简单组',
  'Define horizontal axis group': '定义水平轴组',
  'Define vertical axis group': '定义垂直轴组',
  'Ungroup': '取消分组',
  'Axis': '轴',
  'TimeLine': '时间轴',
  'Create axis group': '创建轴组',
  'Add time point': '添加时间点',
  'Edit time point': '编辑时间点',
  'Delete time point': '删除时间点',
  'Text position': '文字位置',
  'CENTER': '中央',
  'TOP': '上',
  'TOP_RIGHT': '右上',
  'RIGHT': '右',
  'BOTTOM_RIGHT': '右下',
  'BOTTOM': '下',
  'BOTTOM_LEFT': '左下',
  'LEFT': '左',
  'TOP_LEFT': '左上',
  'Click the Marker Icon': '点击标记图标',
  'HOLLOW-CIRCLE': '空心圈',
  'LINE-ARROW': '线箭头',
  'HOLLOW-ARROW': '空心箭头',
  'ARROW': '箭头',
  'HOLLOW-RHOMBUS': '空心菱形',
  'Chat record': '聊天记录',
  'Nothing to edit': '没什么可编辑的',
  'Archives': '档案',
  'HORIZONTAL2': '水平',
  'VERTICAL2': '垂直',
  'Web page': '网页',
  'Total items': '总数',
  'Workbench': '工作区',
  'Source': '来源',
  'Content': '内容',
  '_Content': '内容',
  'Assignment': '任务',
  'Deselect': '取消选择',
  'Summary': '摘要',
  'Student': '学生',
  'Faculty': '教师',
  'List of Pages': '页面清单',
  'Loading notebook': '正在加载笔记本',
  'Showing list': '显示清单',
  'Annotate': '注释',
  'Clipboard': '剪贴板',
  'Row': '行',
  'Column': '栏',
  'Value': '值',
  'Table Header': '表头',
  'New Table': '新表',
  'Add Table': '添加表格',
  'Newsletter': '通讯',
  'Questions? Go ahead.': '你有任何问题吗？请联系我们。',
  'Send': '发信息',
  'Message': '讯息',
  'Subject': '主题',
  'Email': '电子邮件地址',
  'Contact': '联系方式',
  'ERROR LOGIN FAILED': '错误：登录失败',
  'ERROR NOT LOGGED IN': '错误：未登录',
  'ERROR NOTE DIR NOT DEFINED': '错误：笔记本目录未定义',
  'ERROR RESOURCE DIR NOT DEFINED': '错误：资源目录未定义',
  'ERROR EMPTY KEYWORD': '错误：空关键字',
  'SUCCESS NOTE REMOVED': '成功：笔记本已删除',
  'SUCCESS RESOURCE REMOVED': '成功：资源已删除',
  'SUCCESS RESOURCE UPDATED': '成功：资源已更新',
  'ERROR NOTE NOT REMOVED': '错误：未删除笔记本',
  'ERROR RESOURCE NOT UPDATED': '错误：资源未更新',
  'ERROR RESOURCE NOT REMOVED': '错误：资源未删除',
  'Bring forward': '置于前面',
  'Send backward': '置于后面',
  'You are logged in.': '您已登录。',
  'You are logged out.': '您已注销。',
  'Do you want to log out?': '您要登出吗？',
  'Align Top': '顶部对齐',
  'Align Bottom': '底部对齐',
  'Align Right': '右对齐',
  'Align Left': '左对齐',
  'Click to open window': '点击打开窗口',
  'Comment': '说明',
  'Background': '背景',
  'Sourceposition': '起点位置',
  'Targetposition': '终点位置',
  'Info': '信息',
  'OpenWindow': '在新窗口中打开',
  'CloseWindow': '关闭窗口',
  'OpenNewTab': '在新标签页中打开',
  'NORMAL': '普通',
  'HORIZONTAL': '水平',
  'VERTICAL': '垂直',
  'SOLID': '实线',
  'DOTTED': '点线',
  'DASHED': '虚线',
  'LONG-DASHED': '长虚线',
  'Stroke': '线型',
  'erase': '删除',
  'bloom': '展开',
  'wilt': '折叠',
  'Bloom': '展开',
  'Wilt': '折叠',
  'move': '移动',
  'drag': '移动',
  'and': '和',
  '-': '-',
  '+': '+',
  'Abbreviation': '缩写',
  'About': '关于',
  'addContent': '加入内容',
  'addSimpleContent': '加入内容',
  'Add Content': '加入内容',
  'Add New Topic with Style of This Palette': '添加新的主题与此调色板风格',
  'addTopic': '添加主题',
  'addSimpleTopic': '添加主题',
  'Add Topic': '添加主题',
  'Adjust Size': '调整大小',
  'Align Horizontal': '水平对齐',
  'Align Vertical': '垂直对齐',
  'All': '所有',
  'Amoeba': '变形虫',
  'Anchor': '锚点',
  'Anchor Mode': '锚点模式',
  'Angle': '角',
  'Anonymous Model': '匿名模型',
  'Anonyous': '匿名',
  'Any unsaved changes will be lost': '任何未保存的更改将丢失',
  'Are you absolutely sure you want to leave': '你真的确认要离开',
  'Are you sure you want to delete the following': '您确定要删除以下',
  'Are you sure you want to delete this notebook?': '你确定你要删除这台笔记本？',
  'Are you sure you want to merge': '你确定你要合并',
  'Arrow Head': '箭头',
  'Associatins': '关联',
  'Association': '关联',
  'Association Role': '关联角色',
  'AUGMENT': '扩展',
  'Blank': '空白',
  'Bloom All Direction': '向所有方向展开',
  'Bloom by Direction': '按方向展开',
  'Blue Memo': '蓝色便签',
  'Cancel': '取消',
  'Close': '关闭',
  'Change': '变化',
  'Change Password': '更改密码',
  'Chat Mode': '协作模式',
  'CIRCLE': '圆形',
  'Citation': '引文',
  'Class': '类',
  'Clear': '清除',
  'Clear Chat Nodes': '清除聊天节点',
  'Clear Screen': '清除屏幕',
  'Clear Selection': '清除选择',
  'Clone': '克隆',
  'Cloud mode editing': '云端编辑模式',
  'Collabolation': '协作',
  'Color': '颜色',
  'COMMIT': '应用',
  'connect': '连接',
  'Resource': '内容',
  'CONTENTS URL': '内容URL',
  'Control Buttons': '控制按钮',
  'Copy': '复制',
  'Copy & Paste': '复制和粘贴',
  'Copyright': '版权',
  'Create & Edit': '创建和编辑',
  'Create Account': '创建账户',
  'Create New': '新建',
  'Creator': '创建者',
  'Curve': '曲线',
  'Curve/Line': '曲线/直线',
  'Cut': '剪切',
  'Dashed': '虚线',
  'Date Picker': '日期选取器',
  'defined by': '作者',
  'Delete': '删除',
  'Deleting information': '正在删除信息',
  'Dialog': '对话',
  'Diameter': '直径',
  'Do you want create new note?': '要创建新笔记吗？',
  'Dotted': '点',
  'Download': '下载',
  'Downloading information': '下载信息',
  'Drawing Mode': '绘图模式',
  'Dynamic Drawing': '动态绘图',
  'e-Book List': '电子书列表',
  'e-Books': '电子书',
  'Edge': '关联线',
  'Edge Shape': '线型',
  'Edit': '编辑',
  'Edit(s) has been made.': '已完成编辑。',
  'Do you want to save edit(s)?': '你想保存编辑吗？',
  'Edit Flock': '编辑组',
  'Edit Memo': '编辑便签',
  'Edit Style': '编辑样式',
  'Editable Mode': '编辑模式',
  'Editing': '编辑',
  'ELLIPSE': '椭圆形',
  'Erase': '删除',
  'Failed': '失败',
  'File Deleted': '文件已删除',
  'File Upload': '文件上传',
  'Filter': '筛选',
  'Filter Association': '筛选关联',
  'Filter Topic': '筛选主题',
  'Find': '发现',
  'Fixation': '重新布局',
  'Flock': '组',
  'Font': '字形',
  'Force All Fixed': '全部固定',
  'Forgot Password?': '忘记密码？',
  'Free Mode': '自由模式',
  'Get Selected Content Style': '获取所选内容风格',
  'Get Selected Edge Style': '获取所选线条样式',
  'Get Style of Selected Item': '获取所选项目的风格',
  'Go to': '到',
  'Green Memo': '绿色备忘录',
  'Group': '组',
  'Height': '高度',
  'Hidden': '隐藏',
  'Hide': '隐藏',
  'Hide All': '全部隐藏',
  'Hide Memo': '隐藏备忘录',
  'Hide Names': '隐藏作者名',
  'Horizontal Axis': '创建水平轴',
  'Horizontal Equal': '横向平等',
  'In case you cannot load iframe contents': '如果无法加载 iframe 内容',
  'Introduction': '介绍',
  'item(s) listed below': '下面列出的项目',
  'Join': '加入组',
  'Keyword': '关键词',
  'Label': '标签',
  'Layout Topics': '排列主题',
  'Leave': '移出组',
  'List': '列表',
  'List of Notebooks': '笔记列表',
  'Load': '加载',
  'Loading information': '加载信息',
  'Local editing mode': '本地编辑模式',
  'Login': '登录',
  'LOGIN FAILED': '登录失败',
  'Logout': '注销',
  'maximum size is': '最大尺寸为',
  'members': '组成员',
  'Memo': '备忘录',
  'Merge': '合并',
  'Miniature': '缩略视图',
  'Miniature Canvas': '缩略视图画布',
  'minimum size is': '最小尺寸是',
  'Model': '模型',
  'More': '更多',
  'Multiple Lines': '多行',
  'Name': '名字',
  'New': '新',
  'New Axis': '新建轴',
  'New Child Topic': '新建子主题',
  'New Citation': '新建引用',
  'New Content': '新建内容',
  'Add Resource': '添加内容',
  'addMemo': '添加备忘录',
  'addSimpleMemo': '添加备忘录',
  'Add Memo': '添加备忘录',
  'New Flock': '新建组',
  'New Note': '新建',
  'New Page': '新建页面',
  'New Topic': '新主题',
  'Not Found.': '未找到',
  'Not Owner': '非作者',
  'Note': '注释',
  'Notebook': '笔记',
  'Notebook name': '笔记名称',
  'Notebook saved in cloud as': '笔记本电脑保存在云中',
  'Notice': '通知',
  'ELLIPAE': '椭圆',
  'Open': '打开',
  'Overwrite': '覆盖',
  'Page Name': '页面名称',
  'Pages': '页面',
  'Password': '密码',
  'Paste': '贴',
  'Pause': '暂停',
  'Pink Memo': '粉色便签',
  'Play': '播放',
  'Please log in.': '请登录。',
  'Please save': '请妥善保存',
  'please wait': '请稍候',
  'Post Page to Chat': '将页面发布到聊天',
  'Post This Page': '发布此页',
  'Presentation': '演示',
  'Prev': '上一页',
  'Private': '私人',
  'Project': '工程',
  'Public': '公开',
  'PUBLIC Notebooks': '公开笔记',
  'Radius': '半径',
  'Randomize Layout': '随机布局',
  'RECTANGLE': '矩形',
  'Redo': '重做',
  'Reference': '参考',
  'Reflesh Chat Nodes': '刷新聊天节点',
  'Refresh': '刷新',
  'Registered Site': '注册网站',
  'Release All Fixed': '全部取消固定',
  'Relevant Page': '相关页面',
  'Reload': '重新加载',
  'Reset View': '重置视图',
  'Reverse': '反',
  'RHOMBUS': '菱形',
  'Role': '角色',
  'Root': '根',
  'ROUNDED': '圆角',
  'SAMBUICHI PEs Office': '三分一PE办公室',
  'Save': '保存',
  'Save As': '保存为',
  'Save New': '保存新',
  'Save Notebook': '保存笔记本',
  'Scatter': '解散组',
  'Scope': '范围',
  'Screenshot': '截图',
  'Search': '搜索',
  'Search Filter': '搜索过滤',
  'Search occurrence for the given (sub)string.': '搜索事件为给定的（子）字符串。',
  'Search the note for the given (sub)string.': '搜索注意对于给定的（子）字符串。',
  'Search topic for the given (sub)string.': '搜索话题，给定（子）字符串。',
  'Select': '选择',
  'Select All': '全选',
  'Select Content': '选择内容',
  'Select Topic': '选择主题',
  'separated with spaces': '用空格隔开',
  'Setting Options': '设置选项',
  'Shape': '形状',
  'Short Cuts': '捷径',
  'Shortcut Keys': '快捷键',
  'Show': '显示',
  'Show All': '显示全部',
  'Size': '尺寸',
  'Solid': '实线',
  'Start': '开始',
  'Static Drawing': '静态图',
  'Straight': '直线',
  'Subwindow': '子窗口',
  'Table': '表',
  'Text': '文本',
  'Text C.': '文字颜色',
  'Text Color': '文字颜色',
  'Text File': '文本文件',
  'The notebook was deleted successfully.': '笔记本电脑被成功删除。',
  'The selected notebook could not be deleted from the cloud service!': '所选择的笔记本电脑无法从云服务中删除！',
  'The selected notebook could not be loaded from the cloud service!': '所选的笔记本无法从云服务装！',
  'This is the Navigation Window.': '这是导航窗口。\n这里始终显示整个笔记本，当前视口会以红色边框标出。点击即可移动视口。',
  'THUMBNAIL': '缩略图',
  'Timemachine': '时间机器',
  'Toggle': '切换',
  'Toggle Anchor': '切换锚',
  'Toggle Chat': '切换聊天',
  'Toggle Fix': '切换修复',
  'Toggle Search': '切换搜索',
  'Topic': '话题',
  'Topic Categoly': '主题分类',
  'Topics': '主题',
  'TRIANGLE': '三角形',
  'Tree': '树状图',
  'Try again after logging in': '登录后再试',
  'Tutorial': '教程',
  'Un/Directed': '有向/无向',
  'undefined': '未定义',
  'Undirected Bloom': '无向展开',
  'Undo': '复原',
  'Upload': '上传',
  'Upload File': '上传文件',
  'Upload Model ': '上传模式',
  'Upload Pdf Annotations': '上传PDF注释',
  'Uploaded': '上传完成',
  'URL': 'URL',
  'User ID': '用户ID',
  'User Name': '用户名',
  'Vertical Axis': '创建垂直轴',
  'Vertical Equal': '垂直对齐',
  'View': '视图',
  'View Notebook XML': '查看笔记 XML',
  'Visible': '可见',
  'Webcat Plus': 'Webcat Plus',
  'White Memo': '白色便签',
  'Width': '宽度',
  'World Encyclopedia': '世界百科全书',
  'WuWei & PDF Annotation': 'WuWei 与 PDF 注释',
  'WuWei Manual': 'WuWei 手册',
  'WuWei Tutorial': 'WuWei 教程',
  'You are logged in as': '当前登录用户',
  'You may try to tap SOURCE link to view contents directly.': '您可以尝试点击 SOURCE 链接直接查看内容。',
  'You need to log in before saving. Try to save again after logging in!': '您需要在保存之前登录。尝试登录后再次保存！',
  'You need to log in to reach your private notebooks': '您需要登录到您的私人笔记本电脑',
  'You need to log in to use notebooks': '您需要登录才能使用笔记本电脑',
  'Your PRIVATE Notebooks': '你的私人笔记',
  'Zoom': '放大',
  'Create a personal content collection and annotate it.': '创建个人内容集合并添加注释。',
  'Visual notes will help you organize your thoughts.': '视觉化笔记可帮助你整理想法。'
};
