/**
 * wuwei.nls.EN.js
 * EN translation map
 *
 * Revised against JA baseline on 2026-04-17.
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 **/
wuwei.nls.EN = {
  'Publish': 'Publish',
  'Align': 'Align',
  'Define / Ungroup': 'Define / Ungroup',
  'Other': 'Other',
  'Published': 'Published',
  'Public URL': 'Public URL',
  'Open in new tab': 'Open in new tab',
  'Copy URL': 'Copy URL',
  'Copied': 'Copied',
  'Published note is view-only. Editing, saving, and downloading are disabled.': 'Published note is view-only. Editing, saving, and downloading are disabled.',
  'Disabled': 'Disabled',
  'Download note file': 'Download note file',
  'Discard': 'Discard',
  'Discard current note without saving?': 'Discard current note without saving?',
  'Discarded current note': 'Discarded current note',
  'Upload note file': 'Upload note file',
  'Imported note file': 'Imported note file',
  'Add Page': 'Add Page',
  'Select a page and edit its name.': 'Select a page and edit its name.',
  'Select a page to copy.': 'Select a page to copy.',
  'Select a page to open, edit, copy, or delete.': 'Select a page to open, edit, copy, or delete.',
  'WuWei Home': 'WuWei Home',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.',
  'Search content': 'Search content',
  'Calendar': 'Calendar',
  'Commands': 'Commands',
  'Comment to capture your viewpoint before opening a note.': 'Comment to capture your viewpoint before opening a note.',
  'Content gallery': 'Content gallery',
  'Add to note': 'Add to note',
  'Start date': 'Start date',
  'End date': 'End date',
  'Range target': 'Range target',
  'All content in range': 'All content in range',
  'Selected content in range': 'Selected content in range',
  'Search scope': 'Search scope',
  'Current period': 'Current period',
  'All registered content': 'All registered content',
  'Apply': 'Apply',
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': 'Create a new note from the selected content? Unsaved changes in the current note will be discarded.',
  'Selected content': 'Selected content',
  'Open note': 'Open note',
  'New note': 'New note',
  'No comment yet': 'No comment yet',
  'Click a card to preview the content and start working.': 'Click a card to preview the content and start working.',
  'No content in selected period': 'No content in selected period',
  'Upload content or choose another date from the calendar.': 'Upload content or choose another date from the calendar.',
  'Selected day': 'Selected day',
  'Month': 'Month',
  'Showing': 'Showing',
  'Date': 'Date',
  'Type': 'Type',
  'Title': 'Title',
  'Failed to save comment': 'Failed to save comment',
  'Format': 'Format',
  'Saved': 'Saved',
  'This site refused iframe preview.': 'This site refused iframe preview.',
  'Delete this timeline segment?': 'Delete this timeline segment?',
  'OpenPlayer': 'Open player',
  'Create timeline axis': 'Create timeline axis',
  'Axis properties': 'Axis properties',
  'Add segment from player': 'Add segment from player',
  'Segment properties': 'Segment properties',
  'Edit segment from player': 'Edit segment from player',
  'Delete segment': 'Delete segment',
  'Info Timeline Segment': 'Timeline info',
  'SelectAll': 'Select all',
  'Show All Memo': 'Show all memos',
  'Hide All Memo': 'Hide all memos',
  'Note Page': 'Page info',
  'Select shape': 'Select shape',
  'Select font size': 'Select font size',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open Player.',
  'Timeline axis': 'Timeline axis',
  'Media': 'Media',
  'Direction': 'Direction',
  'horizontal': 'Horizontal',
  'vertical': 'Vertical',
  'Media length': 'Media length',
  'Default play duration': 'Default play duration',
  'Axis length': 'Axis length',
  'Axis width': 'Axis width',
  'Axis color': 'Axis color',
  'Timeline segment': 'Timeline segment',
  'Video preview': 'Video preview',
  'Set current time to start': 'Set current time to start',
  'Set current time to end': 'Set current time to end',
  'Create thumbnail': 'Create thumbnail',
  'Start time': 'Start time',
  'End time': 'End time',
  'or': 'or',
  'Play duration': 'Play duration',
  'info': 'Info',
  'Background Color': 'Background color',
  'Length': 'Length',
  'Segments': 'Segments',
  'Default': 'Default',
  'End': 'End',
  'Image': 'Image',
  'Video': 'Video',
  'Audio': 'Audio',
  'Apply to group': 'Apply to group',
  'Media type': 'Media type',
  'Timeline': 'Timeline',
  'Document': 'Document',
  'Duration': 'Duration',
  'Auto': 'Auto',
  'jump start': 'Jump to start',
  'jump end': 'Jump to end',
  'set start here': 'Set start here',
  'set end here': 'Set end here',
  'apply': 'Apply',
  'Define simple group': 'Define simple group',
  'Define horizontal axis group': 'Define horizontal axis group',
  'Define vertical axis group': 'Define vertical axis group',
  'Ungroup': 'Ungroup',
  'Axis': 'Axis',
  'TimeLine': 'Timeline',
  'Create axis group': 'Create axis group',
  'Add time point': 'Add time point',
  'Edit time point': 'Edit time point',
  'Delete time point': 'Delete time point',
  'Text position': 'Text position',
  'CENTER': 'Center',
  'TOP': 'Top',
  'TOP_RIGHT': 'Top Right',
  'RIGHT': 'Right',
  'BOTTOM_RIGHT': 'Bottom Right',
  'BOTTOM': 'Bottom',
  'BOTTOM_LEFT': 'Bottom Left',
  'LEFT': 'Left',
  'TOP_LEFT': 'Top Left',
  'Click the Marker Icon': 'Click the Marker Icon',
  'HOLLOW-CIRCLE': 'Hollow Circle',
  'LINE-ARROW': 'Line Arrow',
  'HOLLOW-ARROW': 'Hollow Arrow',
  'ARROW': 'Arrow',
  'HOLLOW-RHOMBUS': 'Hollow Rhombus',
  'Chat record': 'Chat record',
  'Nothing to edit': 'Nothing to edit',
  'Archives': 'Archives',
  'HORIZONTAL2': 'Horizontal',
  'VERTICAL2': 'Vertical',
  'Web page': 'Web page',
  'Total items': 'Total items',
  'Workbench': 'Workbench',
  'Source': 'Source',
  'Content': 'Content',
  '_Content': 'Content',
  'Assignment': 'Assignment',
  'Deselect': 'Deselect',
  'Summary': 'Summary',
  'Student': 'Student',
  'Faculty': 'Faculty',
  'List of Pages': 'List of Pages',
  'Loading notebook': 'Loading notebook',
  'Showing list': 'Showing list',
  'Annotate': 'Annotate',
  'Clipboard': 'Clipboard',
  'Row': 'Row',
  'Column': 'Column',
  'Value': 'Value',
  'Table Header': 'Table Header',
  'New Table': 'New Table',
  'Add Table': 'Add Table',
  'Newsletter': 'Newsletter',
  'Questions? Go ahead.': 'Do you have any questions? Please contact us.',
  'Send': 'Send',
  'Message': 'Message',
  'Subject': 'Subject',
  'Email': 'Email',
  'Contact': 'Contact',
  'ERROR LOGIN FAILED': 'ERROR: LOGIN FAILED',
  'ERROR NOT LOGGED IN': 'ERROR: NOT LOGGED IN',
  'ERROR NOTE DIR NOT DEFINED': 'ERROR: NOTEBOOK DIR NOT DEFINED',
  'ERROR RESOURCE DIR NOT DEFINED': 'ERROR: RESOURCE DIR NOT DEFINED',
  'ERROR EMPTY KEYWORD': 'ERROR: EMPTY KEYWORD',
  'SUCCESS NOTE REMOVED': 'SUCCESS: NOTEBOOK REMOVED',
  'SUCCESS RESOURCE REMOVED': 'SUCCESS: RESOURCE REMOVED',
  'SUCCESS RESOURCE UPDATED': 'SUCCESS: RESOURCE UPDATED',
  'ERROR NOTE NOT REMOVED': 'ERROR: NOTEBOOK NOT REMOVED',
  'ERROR RESOURCE NOT UPDATED': 'ERROR: RESOURCE NOT UPDATED',
  'ERROR RESOURCE NOT REMOVED': 'ERROR: RESOURCE NOT REMOVED',
  'Bring forward': 'Bring forward',
  'Send backward': 'Send backward',
  'You are logged in.': 'You are logged in.',
  'You are logged out.': 'You are logged out.',
  'Do you want to log out?': 'Do you want to log out?',
  'Align Top': 'Align Top',
  'Align Bottom': 'Align Bottom',
  'Align Right': 'Align Right',
  'Align Left': 'Align Left',
  'Click to open window': 'Click to open window',
  'Comment': 'Comment',
  'Background': 'Background',
  'Sourceposition': 'Source position',
  'Targetposition': 'Target position',
  'Info': 'Information',
  'OpenWindow': 'Open new window',
  'CloseWindow': 'Close window',
  'OpenNewTab': 'Open new tab',
  'NORMAL': 'Normal',
  'HORIZONTAL': 'Horizontal',
  'VERTICAL': 'Vertical',
  'SOLID': 'Solid',
  'DOTTED': 'Dotted',
  'DASHED': 'Dashed',
  'LONG-DASHED': 'Long dashed',
  'Stroke': 'Stroke',
  'erase': 'Erase',
  'bloom': 'Expand',
  'wilt': 'Collapse',
  'Bloom': 'Expand',
  'Wilt': 'Collapse',
  'move': 'move',
  'drag': 'move',
  'and': 'and',
  '-': '-',
  '+': '+',
  'Abbreviation': 'Abbreviation',
  'About': 'About',
  'addContent': 'Add Content',
  'addSimpleContent': 'Add Content',
  'Add Content': 'Add Content',
  'Add New Topic with Style of This Palette': 'Add New Topic with Style of This Palette',
  'addTopic': 'Add Topic',
  'addSimpleTopic': 'Add Topic',
  'Add Topic': 'Add Topic',
  'Adjust Size': 'Adjust Size',
  'Align Horizontal': 'Align Horizontal',
  'Align Vertical': 'Align Vertical',
  'All': 'All',
  'Amoeba': 'Amoeba',
  'Anchor': 'Anchor',
  'Anchor Mode': 'Anchor Mode',
  'Angle': 'Angle',
  'Anonymous Model': 'Anonymous Model',
  'Anonyous': 'Anonymous',
  'Any unsaved changes will be lost': 'Any unsaved changes will be lost',
  'Are you absolutely sure you want to leave': 'Are you absolutely sure you want to leave',
  'Are you sure you want to delete the following': 'Are you sure you want to delete the following',
  'Are you sure you want to delete this notebook?': 'Are you sure you want to delete this notebook?',
  'Are you sure you want to merge': 'Are you sure you want to merge',
  'Arrow Head': 'Arrow Head',
  'Associatins': 'Associations',
  'Association': 'Association',
  'Association Role': 'Association Role',
  'AUGMENT': 'AUGMENT',
  'Blank': 'Blank',
  'Bloom All Direction': 'Bloom All Direction',
  'Bloom by Direction': 'Bloom by Direction',
  'Blue Memo': 'Blue Memo',
  'Cancel': 'Cancel',
  'Close': 'Close',
  'Change': 'Change',
  'Change Password': 'Change Password',
  'Chat Mode': 'Chat Mode',
  'CIRCLE': 'CIRCLE',
  'Citation': 'Citation',
  'Class': 'Class',
  'Clear': 'Clear',
  'Clear Chat Nodes': 'Clear Chat Nodes',
  'Clear Screen': 'Clear Screen',
  'Clear Selection': 'Clear Selection',
  'Clone': 'Clone',
  'Cloud mode editing': 'Cloud mode editing',
  'Collabolation': 'Collaboration',
  'Color': 'Color',
  'COMMIT': 'COMMIT',
  'connect': 'Connect',
  'Resource': 'Resource',
  'CONTENTS URL': 'CONTENTS URL',
  'Control Buttons': 'Control Buttons',
  'Copy': 'Copy',
  'Copy & Paste': 'Copy & Paste',
  'Copyright': 'Copyright',
  'Create & Edit': 'Create & Edit',
  'Create Account': 'Create Account',
  'Create New': 'Create New',
  'Creator': 'Creator',
  'Curve': 'Curve',
  'Curve/Line': 'Curve/Line',
  'Cut': 'Cut',
  'Dashed': 'Dashed',
  'Date Picker': 'Date Picker',
  'defined by': 'defined by',
  'Delete': 'Delete',
  'Deleting information': 'Deleting information',
  'Dialog': 'Dialog',
  'Diameter': 'Diameter',
  'Do you want create new note?': 'Do you want create new notebook?',
  'Dotted': 'Dotted',
  'Download': 'Download',
  'Downloading information': 'Downloading information',
  'Drawing Mode': 'Drawing Mode',
  'Dynamic Drawing': 'Dynamic Drawing',
  'e-Book List': 'e-Book List',
  'e-Books': 'e-Books',
  'Edge': 'Edge',
  'Edge Shape': 'Edge Shape',
  'Edit': 'Edit',
  'Edit(s) has been made.': 'Edit(s) has been made.',
  'Do you want to save edit(s)?': 'Do you want to save edit(s)?',
  'Edit Flock': 'Edit Flock',
  'Edit Memo': 'Edit Memo',
  'Edit Style': 'Edit Style',
  'Editable Mode': 'Editable Mode',
  'Editing': 'Editing',
  'ELLIPSE': 'ELLIPSE',
  'Erase': 'Erase',
  'Failed': 'Failed',
  'File Deleted': 'File Deleted',
  'File Upload': 'File Upload',
  'Filter': 'Filter',
  'Filter Association': 'Filter Association',
  'Filter Topic': 'Filter Topic',
  'Find': 'Find',
  'Fixation': 'Fixation',
  'Flock': 'Flock',
  'Font': 'Font',
  'Force All Fixed': 'Force All Fixed',
  'Forgot Password?': 'Forgot Password?',
  'Free Mode': 'Free Mode',
  'Get Selected Content Style': 'Get Selected Content Style',
  'Get Selected Edge Style': 'Get Selected Edge Style',
  'Get Style of Selected Item': 'Get Style of Selected Item',
  'Go to': 'Go to',
  'Green Memo': 'Green Memo',
  'Group': 'Group',
  'Height': 'Height',
  'Hidden': 'Hidden',
  'Hide': 'Hide',
  'Hide All': 'Hide All',
  'Hide Memo': 'Hide Memo',
  'Hide Names': 'Hide Names',
  'Horizontal Axis': 'Horizontal Axis',
  'Horizontal Equal': 'Horizontal Equal',
  'In case you cannot load iframe contents': 'In case you cannot load iframe contents',
  'Introduction': 'Introduction',
  'item(s) listed below': 'item(s) listed below',
  'Join': 'Join',
  'Keyword': 'Keyword',
  'Label': 'Label',
  'Layout Topics': 'Layout Topics',
  'Leave': 'Leave',
  'List': 'List',
  'List of Notebooks': 'List of Notebooks',
  'Load': 'Load',
  'Loading information': 'Loading information',
  'Local editing mode': 'Local editing mode',
  'Login': 'Login',
  'LOGIN FAILED': 'LOGIN FAILED',
  'Logout': 'Logout',
  'maximum size is': 'maximum size is',
  'members': 'members',
  'Memo': 'Memo',
  'Merge': 'Merge',
  'Miniature': 'Miniature',
  'Miniature Canvas': 'Miniature Canvas',
  'minimum size is': 'minimum size is',
  'Model': 'Model',
  'More': 'More',
  'Multiple Lines': 'Multiple Lines',
  'Name': 'Name',
  'New': 'New',
  'New Axis': 'New Axis',
  'New Child Topic': 'New Child Topic',
  'New Citation': 'New Citation',
  'New Content': 'New Content',
  'Add Resource': 'Add Resource',
  'addMemo': 'Add Memo',
  'addSimpleMemo': 'Add Memo',
  'Add Memo': 'Add Memo',
  'New Flock': 'New Flock',
  'New Note': 'New Notebook',
  'New Page': 'New Page',
  'New Topic': 'New Topic',
  'Not Found.': 'Not Found.',
  'Not Owner': 'Not Owner',
  'Note': 'Note',
  'Notebook': 'Notebook',
  'Notebook name': 'Notebook name',
  'Notebook saved in cloud as': 'Notebook saved in cloud as',
  'Notice': 'Notice',
  'ELLIPAE': 'ELLIPSE',
  'Open': 'Open',
  'Overwrite': 'Overwrite',
  'Page Name': 'Page Name',
  'Pages': 'Pages',
  'Password': 'Password',
  'Paste': 'Paste',
  'Pause': 'Pause',
  'Pink Memo': 'Pink Memo',
  'Play': 'Play',
  'Please log in.': 'Please log in.',
  'Please save': 'Please save',
  'please wait': 'please wait',
  'Post Page to Chat': 'Post Page to Chat',
  'Post This Page': 'Post This Page',
  'Presentation': 'Presentation',
  'Prev': 'Prev.',
  'Private': 'Private',
  'Project': 'Project',
  'Public': 'Public',
  'PUBLIC Notebooks': 'PUBLIC Notebooks',
  'Radius': 'Radius',
  'Randomize Layout': 'Randomize Layout',
  'RECTANGLE': 'RECTANGLE',
  'Redo': 'Redo',
  'Reference': 'Reference',
  'Reflesh Chat Nodes': 'Refresh Chat Nodes',
  'Refresh': 'Refresh',
  'Registered Site': 'Registered Site',
  'Release All Fixed': 'Release All Fixed',
  'Relevant Page': 'Relevant Page',
  'Reload': 'Reload',
  'Reset View': 'Reset View',
  'Reverse': 'Reverse',
  'RHOMBUS': 'RHOMBUS',
  'Role': 'Role',
  'Root': 'Root',
  'ROUNDED': 'ROUNDED',
  'SAMBUICHI PEs Office': 'SAMBUICHI PEs Office',
  'Save': 'Save',
  'Save As': 'Save As',
  'Save New': 'Save New',
  'Save Notebook': 'Save Notebook',
  'Scatter': 'Scatter',
  'Scope': 'Scope',
  'Screenshot': 'Screenshot',
  'Search': 'Search',
  'Search Filter': 'Search Filter',
  'Search occurrence for the given (sub)string.': 'Search occurrence for the given (sub)string.',
  'Search the note for the given (sub)string.': 'Search the notebook for the given (sub)string.',
  'Search topic for the given (sub)string.': 'Search topic for the given (sub)string.',
  'Select': 'Select',
  'Select All': 'Select All',
  'Select Content': 'Select Content',
  'Select Topic': 'Select Topic',
  'separated with spaces': 'separated with spaces',
  'Setting Options': 'Setting Options',
  'Shape': 'Shape',
  'Short Cuts': 'Short Cuts',
  'Shortcut Keys': 'Shortcut Keys',
  'Show': 'Show',
  'Show All': 'Show All',
  'Size': 'Size',
  'Solid': 'Solid',
  'Start': 'Start',
  'Static Drawing': 'Static Drawing',
  'Straight': 'Straight',
  'Subwindow': 'Subwindow',
  'Table': 'Table',
  'Text': 'Text',
  'Text C.': 'Text Color',
  'Text Color': 'Text Color',
  'Text File': 'Text File',
  'The notebook was deleted successfully.': 'The notebook was deleted successfully.',
  'The selected notebook could not be deleted from the cloud service!': 'The selected notebook could not be deleted from the cloud service!',
  'The selected notebook could not be loaded from the cloud service!': 'The selected notebook could not be loaded from the cloud service!',
  'This is the Navigation Window.': 'This is the Navigation Window.\\nIt will always show the whole notebook\\nwith the current viewport shown by\\na red outline. Click to\\nmove the viewport.',
  'THUMBNAIL': 'THUMBNAIL',
  'Timemachine': 'Timemachine',
  'Toggle': 'Toggle',
  'Toggle Anchor': 'Toggle Anchor',
  'Toggle Chat': 'Toggle Chat',
  'Toggle Fix': 'Toggle Fix',
  'Toggle Search': 'Toggle search',
  'Topic': 'Topic',
  'Topic Categoly': 'Topic Category',
  'Topics': 'Topics',
  'TRIANGLE': 'TRIANGLE',
  'Tree': 'Tree',
  'Try again after logging in': 'Try again after logging in',
  'Tutorial': 'Tutorial',
  'Un/Directed': 'Un/Directed',
  'undefined': 'undefined',
  'Undirected Bloom': 'Undirected Bloom',
  'Undo': 'Undo',
  'Upload': 'Upload',
  'Upload File': 'Upload File',
  'Upload Model ': 'Upload Model',
  'Upload Pdf Annotations': 'Upload Pdf Annotations',
  'Uploaded': 'Uploaded',
  'URL': 'URL',
  'User ID': 'User ID',
  'User Name': 'User Name',
  'Vertical Axis': 'Vertical Axis',
  'Vertical Equal': 'Vertical Equal',
  'View': 'View',
  'View Notebook XML': 'View Notebook XML',
  'Visible': 'Visible',
  'Webcat Plus': 'Webcat Plus',
  'White Memo': 'White Memo',
  'Width': 'Width',
  'World Encyclopedia': 'World Encyclopedia',
  'WuWei & PDF Annotation': 'WuWei & PDF Annotation',
  'WuWei Manual': 'WuWei Manual',
  'WuWei Tutorial': 'WuWei Tutorial',
  'You are logged in as': 'You are logged in as',
  'You may try to tap SOURCE link to view contents directly.': 'You may try to tap SOURCE link to view contents directly.',
  'You need to log in before saving. Try to save again after logging in!': 'You need to log in before saving. Try to save again after logging in!',
  'You need to log in to reach your private notebooks': 'You need to log in to reach your private notebooks',
  'You need to log in to use notebooks': 'You need to log in to use notebooks',
  'Your PRIVATE Notebooks': 'Your PRIVATE Notebooks',
  'Zoom': 'Zoom',
  'Create a personal content collection and annotate it.': 'Create a personal content collection and annotate it.',
  'Visual notes will help you organize your thoughts.': 'Visual notes will help you organize your thoughts.'
};
