/**
 * wuwei.nls.ET.js
 * ET translation map
 *
 * Revised against JA baseline on 2026-04-17.
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 **/
wuwei.nls.ET = {
  'Publish': 'Avalda',
  'Align': 'Joondus',
  'Define / Ungroup': 'Määra / tühista rühmitus',
  'Other': 'Muu',
  'Discard': 'Discard',
  'Discard current note without saving?': 'Discard current note without saving?',
  'Discarded current note': 'Discarded current note',
  'Published': 'Published',
  'Public URL': 'Public URL',
  'Open in new tab': 'Open in new tab',
  'Copy URL': 'Copy URL',
  'Copied': 'Copied',
  'Published note is view-only. Editing, saving, and downloading are disabled.': 'Published note is view-only. Editing, saving, and downloading are disabled.',
  'Disabled': 'Disabled',
  'Download note file': 'Download note file',
  'Upload note file': 'Upload note file',
  'Imported note file': 'Imported note file',
  'Add Page': 'Add Page',
  'Select a page and edit its name.': 'Select a page and edit its name.',
  'Select a page to copy.': 'Select a page to copy.',
  'Select a page to open, edit, copy, or delete.': 'Select a page to open, edit, copy, or delete.',
  'WuWei Home': 'WuWei Home',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.',
  'Search content': 'Search content',
  'Calendar': 'Calendar',
  'Commands': 'Commands',
  'Comment to capture your viewpoint before opening a note.': 'Comment to capture your viewpoint before opening a note.',
  'Content gallery': 'Content gallery',
  'Add to note': 'Add to note',
  'Start date': 'Start date',
  'End date': 'End date',
  'Range target': 'Range target',
  'All content in range': 'All content in range',
  'Selected content in range': 'Selected content in range',
  'Search scope': 'Search scope',
  'Current period': 'Current period',
  'All registered content': 'All registered content',
  'Apply': 'Apply',
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': 'Create a new note from the selected content? Unsaved changes in the current note will be discarded.',
  'Selected content': 'Selected content',
  'Open note': 'Open note',
  'New note': 'New note',
  'No comment yet': 'No comment yet',
  'Click a card to preview the content and start working.': 'Click a card to preview the content and start working.',
  'No content in selected period': 'No content in selected period',
  'Upload content or choose another date from the calendar.': 'Upload content or choose another date from the calendar.',
  'Selected day': 'Selected day',
  'Month': 'Month',
  'Showing': 'Showing',
  'Date': 'Kuupäev',
  'Type': 'Tüüp',
  'Title': 'Title',
  'Failed to save comment': 'Failed to save comment',
  'Format': 'Format',
  'Saved': 'Saved',
  'This site refused iframe preview.': 'This site refused iframe preview.',
  'Delete this timeline segment?': 'Kas kustutada see ajajoone lõik?',
  'OpenPlayer': 'Ava mängijas',
  'Create timeline axis': 'Loo ajatelg',
  'Axis properties': 'Telje omadused',
  'Add segment from player': 'Lisa lõik mängijast',
  'Segment properties': 'Lõigu omadused',
  'Edit segment from player': 'Muuda lõiku mängijast',
  'Delete segment': 'Kustuta lõik',
  'Info Timeline Segment': 'Ajatelje teave',
  'SelectAll': 'Vali kõik',
  'Show All Memo': 'Näita kõiki memosid',
  'Hide All Memo': 'Peida kõik memod',
  'Note Page': 'Lehe teave',
  'Select shape': 'Vali kuju',
  'Select font size': 'Vali fondi suurus',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'iframe-i eelvaade ei loe praegust/esitusasendit, vaid salvestab algus- ja lõpuaja ning kasutab Open Playerit.',
  'Timeline axis': 'Ajajoone telg',
  'Media': 'Meedia',
  'Direction': 'Suund',
  'horizontal': 'Horisontaalne',
  'vertical': 'Vertikaalne',
  'Media length': 'Meedia pikkus',
  'Default play duration': 'Vaikimisi esituse kestus',
  'Axis length': 'Telje pikkus',
  'Axis width': 'Telje laius',
  'Axis color': 'Telje värv',
  'Timeline segment': 'Ajajoone lõik',
  'Video preview': 'Video eelvaade',
  'Set current time to start': 'Sea praegune aeg algusajaks',
  'Set current time to end': 'Sea praegune aeg lõpuajaks',
  'Create thumbnail': 'Loo pisipilt',
  'Start time': 'Algusaeg',
  'End time': 'Lõppaeg',
  'or': 'või',
  'Play duration': 'Esituse kestus',
  'info': 'Info',
  'Background Color': 'Taustavärv',
  'Length': 'Pikkus',
  'Segments': 'Lõikude arv',
  'Default': 'Vaikimisi',
  'End': 'Lõpp',
  'Image': 'Pilt',
  'Video': 'Video',
  'Audio': 'Heli',
  'Apply to group': 'Rakenda rühmale',
  'Media type': 'Meedia tüüp',
  'Timeline': 'Ajajoon',
  'Document': 'Dokument',
  'Duration': 'Kestus',
  'Auto': 'Automaatne',
  'jump start': 'Liigu algusesse',
  'jump end': 'Liigu lõppu',
  'set start here': 'Määra siia algus',
  'set end here': 'Määra siia lõpp',
  'apply': 'Rakenda',
  'Define simple group': 'Määra lihtne rühm',
  'Define horizontal axis group': 'Määra horisontaaltelje rühm',
  'Define vertical axis group': 'Määra vertikaaltelje rühm',
  'Ungroup': 'Tühista rühmitus',
  'Axis': 'Telg',
  'TimeLine': 'Ajajoon',
  'Create axis group': 'Loo telje rühm',
  'Add time point': 'Lisa ajapunkt',
  'Edit time point': 'Muuda ajapunkti',
  'Delete time point': 'Kustuta ajapunkt',
  'Text position': 'Teksti asukoht',
  'CENTER': 'Keskel',
  'TOP': 'Ülal',
  'TOP_RIGHT': 'Ülal paremal',
  'RIGHT': 'Paremal',
  'BOTTOM_RIGHT': 'All paremal',
  'BOTTOM': 'All',
  'BOTTOM_LEFT': 'All vasakul',
  'LEFT': 'Vasakul',
  'TOP_LEFT': 'Ülal vasakul',
  'Click the Marker Icon': 'Klõpsa markeriikooni',
  'HOLLOW-CIRCLE': 'Hollow Circle',
  'LINE-ARROW': 'Line Arrow',
  'HOLLOW-ARROW': 'Hollow Arrow',
  'ARROW': 'Arrow',
  'HOLLOW-RHOMBUS': 'Hollow Rhombus',
  'Chat record': 'Vestluse ajalugu',
  'Nothing to edit': 'Pole midagi muuta',
  'Archives': 'Arhiivid',
  'HORIZONTAL2': 'Horisontaalne',
  'VERTICAL2': 'Vertikaalne',
  'Web page': 'Veebileht',
  'Total items': 'Elemente kokku',
  'Workbench': 'Töölaud',
  'Source': 'Allikas',
  'Content': 'Sisu',
  '_Content': 'Sisu',
  'Assignment': 'Ülesanne',
  'Deselect': 'Tühista valik',
  'Summary': 'Kokkuvõte',
  'Student': 'Üliõpilane',
  'Faculty': 'Õppejõud',
  'List of Pages': 'Lehtede loend',
  'Loading notebook': 'Märkmikku laaditakse',
  'Showing list': 'Loendi kuvamine',
  'Annotate': 'Lisa märkus',
  'Clipboard': 'Lõikelaud',
  'Row': 'Rida',
  'Column': 'Veerg',
  'Value': 'Väärtus',
  'Table Header': 'Tabeli päis',
  'New Table': 'Uus tabel',
  'Add Table': 'Lisa tabel',
  'Newsletter': 'Uudiskiri',
  'Questions? Go ahead.': 'Kas teil on küsimusi? Võtke meiega ühendust.',
  'Send': 'Saada',
  'Message': 'Sõnum',
  'Subject': 'Teema',
  'Email': 'E-post',
  'Contact': 'Kontakt',
  'ERROR LOGIN FAILED': 'VIGA: sisselogimine ebaõnnestus',
  'ERROR NOT LOGGED IN': 'VIGA: pole sisse logitud',
  'ERROR NOTE DIR NOT DEFINED': 'VIGA: märkmiku kataloog pole määratud',
  'ERROR RESOURCE DIR NOT DEFINED': 'VIGA: ressursi kataloog pole määratud',
  'ERROR EMPTY KEYWORD': 'VIGA: tühi märksõna',
  'SUCCESS NOTE REMOVED': 'ÕNNESTUS: märkmik kustutati',
  'SUCCESS RESOURCE REMOVED': 'ÕNNESTUS: ressurss kustutati',
  'SUCCESS RESOURCE UPDATED': 'ÕNNESTUS: ressurss uuendati',
  'ERROR NOTE NOT REMOVED': 'VIGA: märkmikku ei kustutatud',
  'ERROR RESOURCE NOT UPDATED': 'VIGA: ressurssi ei uuendatud',
  'ERROR RESOURCE NOT REMOVED': 'VIGA: ressurssi ei kustutatud',
  'Bring forward': 'Too ettepoole',
  'Send backward': 'Saada tahapoole',
  'You are logged in.': 'Olete sisse logitud.',
  'You are logged out.': 'Olete välja logitud.',
  'Do you want to log out?': 'Kas soovite välja logida?',
  'Align Top': 'Joonda ülaossa',
  'Align Bottom': 'Joonda alla',
  'Align Right': 'Joonda paremale',
  'Align Left': 'Joonda vasakule',
  'Click to open window': 'Klõpsa akna avamiseks',
  'Comment': 'Kommentaar',
  'Background': 'Taust',
  'Sourceposition': 'Lähteasukoht',
  'Targetposition': 'Sihtasukoht',
  'Info': 'Info',
  'OpenWindow': 'Ava uues aknas',
  'CloseWindow': 'Sulge aken',
  'OpenNewTab': 'Ava uuel vahelehel',
  'NORMAL': 'Tavaline',
  'HORIZONTAL': 'Horisontaalne',
  'VERTICAL': 'Vertikaalne',
  'SOLID': 'Pidev',
  'DOTTED': 'Punktiir',
  'DASHED': 'Katkendlik',
  'LONG-DASHED': 'Pikk katkendlik',
  'Stroke': 'Joone tüüp',
  'erase': 'Kustuta',
  'bloom': 'Laienda',
  'wilt': 'Ahenda',
  'Bloom': 'Laienda',
  'Wilt': 'Ahenda',
  'move': 'Liiguta',
  'drag': 'Liiguta',
  'and': 'ja',
  '-': '-',
  '+': '+',
  'Abbreviation': 'Lühend',
  'About': 'Teave',
  'addContent': 'Lisa sisu',
  'addSimpleContent': 'Lisa sisu',
  'Add Content': 'Lisa sisu',
  'Add New Topic with Style of This Palette': 'Lisa uus teema selle paleti stiiliga',
  'addTopic': 'Lisa teema',
  'addSimpleTopic': 'Lisa teema',
  'Add Topic': 'Lisa teema',
  'Adjust Size': 'Muuda suurust',
  'Align Horizontal': 'Joonda horisontaalselt',
  'Align Vertical': 'Joonda vertikaalselt',
  'All': 'Kõik',
  'Amoeba': 'Amööb',
  'Anchor': 'Ankur',
  'Anchor Mode': 'Ankrurežiim',
  'Angle': 'Nurk',
  'Anonymous Model': 'Anonüümne mudel',
  'Anonyous': 'Anonüümne',
  'Any unsaved changes will be lost': 'Kõik salvestamata muudatused lähevad kaotsi',
  'Are you absolutely sure you want to leave': 'Kas olete kindel, et soovite lahkuda?',
  'Are you sure you want to delete the following': 'Kas soovite kindlasti kustutada järgmise?',
  'Are you sure you want to delete this notebook?': 'Kas soovite selle märkmiku kindlasti kustutada?',
  'Are you sure you want to merge': 'Kas soovite kindlasti ühendada?',
  'Arrow Head': 'Nooleots',
  'Associatins': 'Seosed',
  'Association': 'Seos',
  'Association Role': 'Seose roll',
  'AUGMENT': 'Laienda',
  'Blank': 'Tühi',
  'Bloom All Direction': 'Laienda kõikides suundades',
  'Bloom by Direction': 'Laienda suuna järgi',
  'Blue Memo': 'Sinine märkmepaber',
  'Cancel': 'Loobu',
  'Close': 'Sulge',
  'Change': 'Muuda',
  'Change Password': 'Change Password',
  'Chat Mode': 'Chat Mode',
  'CIRCLE': 'Ring',
  'Citation': 'Citation',
  'Class': 'Class',
  'Clear': 'Clear',
  'Clear Chat Nodes': 'Clear Chat Nodes',
  'Clear Screen': 'Clear Screen',
  'Clear Selection': 'Clear Selection',
  'Clone': 'Clone',
  'Cloud mode editing': 'Cloud mode editing',
  'Collabolation': 'Collaboration',
  'Color': 'Värv',
  'COMMIT': 'Rakenda',
  'connect': 'Ühenda',
  'Resource': 'Resource',
  'CONTENTS URL': 'CONTENTS URL',
  'Control Buttons': 'Control Buttons',
  'Copy': 'Kopeeri',
  'Copy & Paste': 'Kopeeri ja kleebi',
  'Copyright': 'Autoriõigus',
  'Create & Edit': 'Create & Edit',
  'Create Account': 'Create Account',
  'Create New': 'Loo uus',
  'Creator': 'Looja',
  'Curve': 'Kõver',
  'Curve/Line': 'Kõver/joon',
  'Cut': 'Lõika',
  'Dashed': 'Dashed',
  'Date Picker': 'Date Picker',
  'defined by': 'defined by',
  'Delete': 'Kustuta',
  'Deleting information': 'Deleting information',
  'Dialog': 'Dialoog',
  'Diameter': 'Läbimõõt',
  'Do you want create new note?': 'Do you want create new notebook?',
  'Dotted': 'Dotted',
  'Download': 'Laadi alla',
  'Downloading information': 'Downloading information',
  'Drawing Mode': 'Joonistusrežiim',
  'Dynamic Drawing': 'Dynamic Drawing',
  'e-Book List': 'e-Book List',
  'e-Books': 'e-Books',
  'Edge': 'Edge',
  'Edge Shape': 'Edge Shape',
  'Edit': 'Muuda',
  'Edit(s) has been made.': 'Edit(s) has been made.',
  'Do you want to save edit(s)?': 'Do you want to save edit(s)?',
  'Edit Flock': 'Edit Flock',
  'Edit Memo': 'Edit Memo',
  'Edit Style': 'Edit Style',
  'Editable Mode': 'Editable Mode',
  'Editing': 'Muutmine',
  'ELLIPSE': 'Ellips',
  'Erase': 'Erase',
  'Failed': 'Ebaõnnestus',
  'File Deleted': 'File Deleted',
  'File Upload': 'Faili üleslaadimine',
  'Filter': 'Filter',
  'Filter Association': 'Filter Association',
  'Filter Topic': 'Filter Topic',
  'Find': 'Leia',
  'Fixation': 'Fixation',
  'Flock': 'Flock',
  'Font': 'Font',
  'Force All Fixed': 'Force All Fixed',
  'Forgot Password?': 'Forgot Password?',
  'Free Mode': 'Vaba režiim',
  'Get Selected Content Style': 'Get Selected Content Style',
  'Get Selected Edge Style': 'Get Selected Edge Style',
  'Get Style of Selected Item': 'Get Style of Selected Item',
  'Go to': 'Go to',
  'Green Memo': 'Green Memo',
  'Group': 'Rühm',
  'Height': 'Kõrgus',
  'Hidden': 'Peidetud',
  'Hide': 'Peida',
  'Hide All': 'Peida kõik',
  'Hide Memo': 'Hide Memo',
  'Hide Names': 'Hide Names',
  'Horizontal Axis': 'Horizontal Axis',
  'Horizontal Equal': 'Horizontal Equal',
  'In case you cannot load iframe contents': 'In case you cannot load iframe contents',
  'Introduction': 'Tutvustus',
  'item(s) listed below': 'item(s) listed below',
  'Join': 'Join',
  'Keyword': 'Märksõna',
  'Label': 'Silt',
  'Layout Topics': 'Layout Topics',
  'Leave': 'Lahku',
  'List': 'Loend',
  'List of Notebooks': 'List of Notebooks',
  'Load': 'Laadi',
  'Loading information': 'Loading information',
  'Local editing mode': 'Local editing mode',
  'Login': 'Logi sisse',
  'LOGIN FAILED': 'LOGIN FAILED',
  'Logout': 'Logi välja',
  'maximum size is': 'maximum size is',
  'members': 'members',
  'Memo': 'Märkmik',
  'Merge': 'Ühenda',
  'Miniature': 'Miniatuur',
  'Miniature Canvas': 'Miniature Canvas',
  'minimum size is': 'minimum size is',
  'Model': 'Model',
  'More': 'More',
  'Multiple Lines': 'Multiple Lines',
  'Name': 'Nimi',
  'New': 'Uus',
  'New Axis': 'New Axis',
  'New Child Topic': 'New Child Topic',
  'New Citation': 'New Citation',
  'New Content': 'New Content',
  'Add Resource': 'Add Resource',
  'addMemo': 'Lisa märkmepaber',
  'addSimpleMemo': 'Lisa märkmepaber',
  'Add Memo': 'Lisa märkmepaber',
  'New Flock': 'New Flock',
  'New Note': 'Uus märkmik',
  'New Page': 'Uus leht',
  'New Topic': 'Uus teema',
  'Not Found.': 'Not Found.',
  'Not Owner': 'Not Owner',
  'Note': 'Märkus',
  'Notebook': 'Märkmik',
  'Notebook name': 'Notebook name',
  'Notebook saved in cloud as': 'Notebook saved in cloud as',
  'Notice': 'Notice',
  'ELLIPAE': 'Ellips',
  'Open': 'Ava',
  'Overwrite': 'Kirjuta üle',
  'Page Name': 'Lehe nimi',
  'Pages': 'Lehed',
  'Password': 'Parool',
  'Paste': 'Kleebi',
  'Pause': 'Paus',
  'Pink Memo': 'Pink Memo',
  'Play': 'Esita',
  'Please log in.': 'Palun logige sisse.',
  'Please save': 'Palun salvestage',
  'please wait': 'please wait',
  'Post Page to Chat': 'Post Page to Chat',
  'Post This Page': 'Post This Page',
  'Presentation': 'Presentation',
  'Prev': 'Prev.',
  'Private': 'Privaatne',
  'Project': 'Project',
  'Public': 'Avalik',
  'PUBLIC Notebooks': 'PUBLIC Notebooks',
  'Radius': 'Radius',
  'Randomize Layout': 'Randomize Layout',
  'RECTANGLE': 'Ristkülik',
  'Redo': 'Tee uuesti',
  'Reference': 'Reference',
  'Reflesh Chat Nodes': 'Refresh Chat Nodes',
  'Refresh': 'Värskenda',
  'Registered Site': 'Registered Site',
  'Release All Fixed': 'Release All Fixed',
  'Relevant Page': 'Relevant Page',
  'Reload': 'Laadi uuesti',
  'Reset View': 'Lähtesta vaade',
  'Reverse': 'Reverse',
  'RHOMBUS': 'Romb',
  'Role': 'Role',
  'Root': 'Root',
  'ROUNDED': 'Ümarad nurgad',
  'SAMBUICHI PEs Office': 'SAMBUICHI PEs Office',
  'Save': 'Salvesta',
  'Save As': 'Salvesta nimega',
  'Save New': 'Save New',
  'Save Notebook': 'Salvesta märkmik',
  'Scatter': 'Scatter',
  'Scope': 'Scope',
  'Screenshot': 'Screenshot',
  'Search': 'Otsi',
  'Search Filter': 'Otsingufilter',
  'Search occurrence for the given (sub)string.': 'Search occurrence for the given (sub)string.',
  'Search the note for the given (sub)string.': 'Search the notebook for the given (sub)string.',
  'Search topic for the given (sub)string.': 'Search topic for the given (sub)string.',
  'Select': 'Vali',
  'Select All': 'Vali kõik',
  'Select Content': 'Select Content',
  'Select Topic': 'Select Topic',
  'separated with spaces': 'separated with spaces',
  'Setting Options': 'Seaded',
  'Shape': 'Kuju',
  'Short Cuts': 'Short Cuts',
  'Shortcut Keys': 'Shortcut Keys',
  'Show': 'Näita',
  'Show All': 'Näita kõiki',
  'Size': 'Suurus',
  'Solid': 'Solid',
  'Start': 'Algus',
  'Static Drawing': 'Static Drawing',
  'Straight': 'Sirge',
  'Subwindow': 'Subwindow',
  'Table': 'Tabel',
  'Text': 'Tekst',
  'Text C.': 'Teksti värv',
  'Text Color': 'Teksti värv',
  'Text File': 'Text File',
  'The notebook was deleted successfully.': 'The notebook was deleted successfully.',
  'The selected notebook could not be deleted from the cloud service!': 'The selected notebook could not be deleted from the cloud service!',
  'The selected notebook could not be loaded from the cloud service!': 'The selected notebook could not be loaded from the cloud service!',
  'This is the Navigation Window.': 'This is the Navigation Window.\\nIt will always show the whole notebook\\nwith the current viewport shown by\\na red outline. Click to\\nmove the viewport.',
  'THUMBNAIL': 'Pisipilt',
  'Timemachine': 'Timemachine',
  'Toggle': 'Toggle',
  'Toggle Anchor': 'Toggle Anchor',
  'Toggle Chat': 'Toggle Chat',
  'Toggle Fix': 'Toggle Fix',
  'Toggle Search': 'Toggle search',
  'Topic': 'Teema',
  'Topic Categoly': 'Teema kategooria',
  'Topics': 'Teemad',
  'TRIANGLE': 'Kolmnurk',
  'Tree': 'Puu',
  'Try again after logging in': 'Proovige pärast sisselogimist uuesti',
  'Tutorial': 'Õpetus',
  'Un/Directed': 'Un/Directed',
  'undefined': 'undefined',
  'Undirected Bloom': 'Undirected Bloom',
  'Undo': 'Võta tagasi',
  'Upload': 'Laadi üles',
  'Upload File': 'Laadi fail üles',
  'Upload Model ': 'Upload Model',
  'Upload Pdf Annotations': 'Upload Pdf Annotations',
  'Uploaded': 'Uploaded',
  'URL': 'URL',
  'User ID': 'Kasutaja ID',
  'User Name': 'Kasutajanimi',
  'Vertical Axis': 'Vertikaaltelg',
  'Vertical Equal': 'Joonda vertikaalselt',
  'View': 'Vaade',
  'View Notebook XML': 'View Notebook XML',
  'Visible': 'Nähtav',
  'Webcat Plus': 'Webcat Plus',
  'White Memo': 'Valge märkmepaber',
  'Width': 'Laius',
  'World Encyclopedia': 'Maailma entsüklopeedia',
  'WuWei & PDF Annotation': 'WuWei & PDF Annotation',
  'WuWei Manual': 'WuWei juhend',
  'WuWei Tutorial': 'WuWei õpetus',
  'You are logged in as': 'Sisse logitud kasutajana',
  'You may try to tap SOURCE link to view contents directly.': 'You may try to tap SOURCE link to view contents directly.',
  'You need to log in before saving. Try to save again after logging in!': 'You need to log in before saving. Try to save again after logging in!',
  'You need to log in to reach your private notebooks': 'You need to log in to reach your private notebooks',
  'You need to log in to use notebooks': 'You need to log in to use notebooks',
  'Your PRIVATE Notebooks': 'Teie privaatsed märkmikud',
  'Zoom': 'Suum',
  'Create a personal content collection and annotate it.': 'Create a personal content collection and annotate it.',
  'Visual notes will help you organize your thoughts.': 'Visual notes will help you organize your thoughts.'
};
