/**
 * wuwei.nls.FI.js
 * FI translation map
 *
 * Revised against JA baseline on 2026-04-17.
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 **/
wuwei.nls.FI = {
  'Publish': 'Julkaise',
  'Align': 'Tasaus',
  'Define / Ungroup': 'Määritä / pura ryhmä',
  'Other': 'Muut',
  'Discard': 'Discard',
  'Discard current note without saving?': 'Discard current note without saving?',
  'Discarded current note': 'Discarded current note',
  'Published': 'Published',
  'Public URL': 'Public URL',
  'Open in new tab': 'Open in new tab',
  'Copy URL': 'Copy URL',
  'Copied': 'Copied',
  'Published note is view-only. Editing, saving, and downloading are disabled.': 'Published note is view-only. Editing, saving, and downloading are disabled.',
  'Disabled': 'Disabled',
  'Download note file': 'Download note file',
  'Upload note file': 'Upload note file',
  'Imported note file': 'Imported note file',
  'Add Page': 'Add Page',
  'Select a page and edit its name.': 'Select a page and edit its name.',
  'Select a page to copy.': 'Select a page to copy.',
  'Select a page to open, edit, copy, or delete.': 'Select a page to open, edit, copy, or delete.',
  'WuWei Home': 'WuWei Home',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.',
  'Search content': 'Search content',
  'Calendar': 'Calendar',
  'Commands': 'Commands',
  'Comment to capture your viewpoint before opening a note.': 'Comment to capture your viewpoint before opening a note.',
  'Content gallery': 'Content gallery',
  'Add to note': 'Add to note',
  'Start date': 'Start date',
  'End date': 'End date',
  'Range target': 'Range target',
  'All content in range': 'All content in range',
  'Selected content in range': 'Selected content in range',
  'Search scope': 'Search scope',
  'Current period': 'Current period',
  'All registered content': 'All registered content',
  'Apply': 'Apply',
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': 'Create a new note from the selected content? Unsaved changes in the current note will be discarded.',
  'Selected content': 'Selected content',
  'Open note': 'Open note',
  'New note': 'New note',
  'No comment yet': 'No comment yet',
  'Click a card to preview the content and start working.': 'Click a card to preview the content and start working.',
  'No content in selected period': 'No content in selected period',
  'Upload content or choose another date from the calendar.': 'Upload content or choose another date from the calendar.',
  'Selected day': 'Selected day',
  'Month': 'Month',
  'Showing': 'Showing',
  'Date': 'Päivämäärä',
  'Type': 'Tyyppi',
  'Title': 'Title',
  'Failed to save comment': 'Failed to save comment',
  'Format': 'Format',
  'Saved': 'Saved',
  'This site refused iframe preview.': 'This site refused iframe preview.',
  'Delete this timeline segment?': 'Poistetaanko tämä aikajanan jakso?',
  'OpenPlayer': 'Avaa soittimessa',
  'Create timeline axis': 'Luo aikajana-akseli',
  'Axis properties': 'Akselin ominaisuudet',
  'Add segment from player': 'Lisää jakso soittimesta',
  'Segment properties': 'Jakson ominaisuudet',
  'Edit segment from player': 'Muokkaa jaksoa soittimesta',
  'Delete segment': 'Poista jakso',
  'Info Timeline Segment': 'Aikajanan tiedot',
  'SelectAll': 'Valitse kaikki',
  'Show All Memo': 'Näytä kaikki muistiot',
  'Hide All Memo': 'Piilota kaikki muistiot',
  'Note Page': 'Sivun tiedot',
  'Select shape': 'Valitse muoto',
  'Select font size': 'Valitse fonttikoko',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'iframe-esikatselu ei hae nykyistä/toistokohtaa, vaan tallentaa alku- ja loppuajan ja käyttää Open Playeria.',
  'Timeline axis': 'Aikajanan akseli',
  'Media': 'Media',
  'Direction': 'Suunta',
  'horizontal': 'Vaaka',
  'vertical': 'Pysty',
  'Media length': 'Median pituus',
  'Default play duration': 'Oletustoiston kesto',
  'Axis length': 'Akselin pituus',
  'Axis width': 'Akselin leveys',
  'Axis color': 'Akselin väri',
  'Timeline segment': 'Aikajanan jakso',
  'Video preview': 'Videon esikatselu',
  'Set current time to start': 'Aseta nykyinen aika aloitusajaksi',
  'Set current time to end': 'Aseta nykyinen aika lopetusajaksi',
  'Create thumbnail': 'Luo pikkukuva',
  'Start time': 'Aloitusaika',
  'End time': 'Lopetusaika',
  'or': 'tai',
  'Play duration': 'Toiston kesto',
  'info': 'Tiedot',
  'Background Color': 'Taustaväri',
  'Length': 'Pituus',
  'Segments': 'Jaksojen määrä',
  'Default': 'Oletus',
  'End': 'Loppu',
  'Image': 'Kuva',
  'Video': 'Video',
  'Audio': 'Ääni',
  'Apply to group': 'Käytä ryhmään',
  'Media type': 'Mediatyyppi',
  'Timeline': 'Aikajana',
  'Document': 'Asiakirja',
  'Duration': 'Kesto',
  'Auto': 'Automaattinen',
  'jump start': 'Siirry alkuun',
  'jump end': 'Siirry loppuun',
  'set start here': 'Aseta alku tähän',
  'set end here': 'Aseta loppu tähän',
  'apply': 'Käytä',
  'Define simple group': 'Määritä yksinkertainen ryhmä',
  'Define horizontal axis group': 'Määritä vaaka-akselin ryhmä',
  'Define vertical axis group': 'Määritä pystyakselin ryhmä',
  'Ungroup': 'Pura ryhmä',
  'Axis': 'Akseli',
  'TimeLine': 'Aikajana',
  'Create axis group': 'Luo akseliryhmä',
  'Add time point': 'Lisää aikapiste',
  'Edit time point': 'Muokkaa aikapistettä',
  'Delete time point': 'Poista aikapiste',
  'Text position': 'Tekstin sijainti',
  'CENTER': 'Keskellä',
  'TOP': 'Ylhäällä',
  'TOP_RIGHT': 'Ylhäällä oikealla',
  'RIGHT': 'Oikealla',
  'BOTTOM_RIGHT': 'Alhaalla oikealla',
  'BOTTOM': 'Alhaalla',
  'BOTTOM_LEFT': 'Alhaalla vasemmalla',
  'LEFT': 'Vasemmalla',
  'TOP_LEFT': 'Ylhäällä vasemmalla',
  'Click the Marker Icon': 'Napsauta merkkikuvaketta',
  'HOLLOW-CIRCLE': 'Hollow Circle',
  'LINE-ARROW': 'Line Arrow',
  'HOLLOW-ARROW': 'Hollow Arrow',
  'ARROW': 'Arrow',
  'HOLLOW-RHOMBUS': 'Hollow Rhombus',
  'Chat record': 'Chat-historia',
  'Nothing to edit': 'Ei mitään muokattavaa',
  'Archives': 'Arkistot',
  'HORIZONTAL2': 'Vaaka',
  'VERTICAL2': 'Pysty',
  'Web page': 'Verkkosivu',
  'Total items': 'Kohteita yhteensä',
  'Workbench': 'Työtila',
  'Source': 'Lähde',
  'Content': 'Sisältö',
  '_Content': 'Sisältö',
  'Assignment': 'Tehtävä',
  'Deselect': 'Poista valinta',
  'Summary': 'Yhteenveto',
  'Student': 'Opiskelija',
  'Faculty': 'Opettaja',
  'List of Pages': 'Sivuluettelo',
  'Loading notebook': 'Muistikirjaa ladataan',
  'Showing list': 'Näytetään luetteloa',
  'Annotate': 'Lisää merkintä',
  'Clipboard': 'Leikepöytä',
  'Row': 'Rivi',
  'Column': 'Sarake',
  'Value': 'Arvo',
  'Table Header': 'Taulukon otsikko',
  'New Table': 'Uusi taulukko',
  'Add Table': 'Lisää taulukko',
  'Newsletter': 'Uutiskirje',
  'Questions? Go ahead.': 'Onko sinulla kysyttävää? Ota yhteyttä.',
  'Send': 'Lähetä',
  'Message': 'Viesti',
  'Subject': 'Aihe',
  'Email': 'Sähköposti',
  'Contact': 'Yhteystiedot',
  'ERROR LOGIN FAILED': 'VIRHE: kirjautuminen epäonnistui',
  'ERROR NOT LOGGED IN': 'VIRHE: ei kirjautunut sisään',
  'ERROR NOTE DIR NOT DEFINED': 'VIRHE: muistikirjahakemistoa ei ole määritetty',
  'ERROR RESOURCE DIR NOT DEFINED': 'VIRHE: resurssihakemistoa ei ole määritetty',
  'ERROR EMPTY KEYWORD': 'VIRHE: tyhjä avainsana',
  'SUCCESS NOTE REMOVED': 'ONNISTUI: muistikirja poistettiin',
  'SUCCESS RESOURCE REMOVED': 'ONNISTUI: resurssi poistettiin',
  'SUCCESS RESOURCE UPDATED': 'ONNISTUI: resurssi päivitettiin',
  'ERROR NOTE NOT REMOVED': 'VIRHE: muistikirjaa ei poistettu',
  'ERROR RESOURCE NOT UPDATED': 'VIRHE: resurssia ei päivitetty',
  'ERROR RESOURCE NOT REMOVED': 'VIRHE: resurssia ei poistettu',
  'Bring forward': 'Tuo eteen',
  'Send backward': 'Lähetä taakse',
  'You are logged in.': 'Olet kirjautunut sisään.',
  'You are logged out.': 'Olet kirjautunut ulos.',
  'Do you want to log out?': 'Haluatko kirjautua ulos?',
  'Align Top': 'Tasaa ylös',
  'Align Bottom': 'Tasaa alas',
  'Align Right': 'Tasaa oikealle',
  'Align Left': 'Tasaa vasemmalle',
  'Click to open window': 'Avaa ikkuna napsauttamalla',
  'Comment': 'Kommentti',
  'Background': 'Tausta',
  'Sourceposition': 'Lähteen sijainti',
  'Targetposition': 'Kohteen sijainti',
  'Info': 'Tiedot',
  'OpenWindow': 'Avaa uuteen ikkunaan',
  'CloseWindow': 'Sulje ikkuna',
  'OpenNewTab': 'Avaa uudessa välilehdessä',
  'NORMAL': 'Normaali',
  'HORIZONTAL': 'Vaaka',
  'VERTICAL': 'Pysty',
  'SOLID': 'Yhtenäinen',
  'DOTTED': 'Pisteviiva',
  'DASHED': 'Katkoviiva',
  'LONG-DASHED': 'Pitkä katkoviiva',
  'Stroke': 'Viivatyyppi',
  'erase': 'Poista',
  'bloom': 'Laajenna',
  'wilt': 'Kutista',
  'Bloom': 'Laajenna',
  'Wilt': 'Kutista',
  'move': 'Siirrä',
  'drag': 'Siirrä',
  'and': 'ja',
  '-': '-',
  '+': '+',
  'Abbreviation': 'Lyhenne',
  'About': 'Tietoja',
  'addContent': 'Lisää sisältö',
  'addSimpleContent': 'Lisää sisältö',
  'Add Content': 'Lisää sisältö',
  'Add New Topic with Style of This Palette': 'Lisää uusi aihe tämän paletin tyylillä',
  'addTopic': 'Lisää aihe',
  'addSimpleTopic': 'Lisää aihe',
  'Add Topic': 'Lisää aihe',
  'Adjust Size': 'Säädä kokoa',
  'Align Horizontal': 'Tasaa vaakasuunnassa',
  'Align Vertical': 'Tasaa pystysuunnassa',
  'All': 'Kaikki',
  'Amoeba': 'Ameeba',
  'Anchor': 'Ankkuri',
  'Anchor Mode': 'Ankkuritila',
  'Angle': 'Kulma',
  'Anonymous Model': 'Anonyymi malli',
  'Anonyous': 'Anonyymi',
  'Any unsaved changes will be lost': 'Tallentamattomat muutokset menetetään',
  'Are you absolutely sure you want to leave': 'Haluatko varmasti poistua?',
  'Are you sure you want to delete the following': 'Haluatko varmasti poistaa seuraavan?',
  'Are you sure you want to delete this notebook?': 'Haluatko varmasti poistaa tämän muistikirjan?',
  'Are you sure you want to merge': 'Haluatko varmasti yhdistää?',
  'Arrow Head': 'Nuolenkärki',
  'Associatins': 'Yhteydet',
  'Association': 'Yhteys',
  'Association Role': 'Yhteyden rooli',
  'AUGMENT': 'Laajenna',
  'Blank': 'Tyhjä',
  'Bloom All Direction': 'Laajenna kaikkiin suuntiin',
  'Bloom by Direction': 'Laajenna suunnan mukaan',
  'Blue Memo': 'Sininen muistio',
  'Cancel': 'Peruuta',
  'Close': 'Sulje',
  'Change': 'Muuta',
  'Change Password': 'Change Password',
  'Chat Mode': 'Chat Mode',
  'CIRCLE': 'Ympyrä',
  'Citation': 'Citation',
  'Class': 'Class',
  'Clear': 'Clear',
  'Clear Chat Nodes': 'Clear Chat Nodes',
  'Clear Screen': 'Clear Screen',
  'Clear Selection': 'Clear Selection',
  'Clone': 'Clone',
  'Cloud mode editing': 'Cloud mode editing',
  'Collabolation': 'Collaboration',
  'Color': 'Väri',
  'COMMIT': 'Käytä',
  'connect': 'Yhdistä',
  'Resource': 'Resource',
  'CONTENTS URL': 'CONTENTS URL',
  'Control Buttons': 'Control Buttons',
  'Copy': 'Kopioi',
  'Copy & Paste': 'Kopioi ja liitä',
  'Copyright': 'Tekijänoikeus',
  'Create & Edit': 'Create & Edit',
  'Create Account': 'Create Account',
  'Create New': 'Luo uusi',
  'Creator': 'Tekijä',
  'Curve': 'Kaari',
  'Curve/Line': 'Kaari/viiva',
  'Cut': 'Leikkaa',
  'Dashed': 'Dashed',
  'Date Picker': 'Date Picker',
  'defined by': 'defined by',
  'Delete': 'Poista',
  'Deleting information': 'Deleting information',
  'Dialog': 'Valintaikkuna',
  'Diameter': 'Halkaisija',
  'Do you want create new note?': 'Do you want create new notebook?',
  'Dotted': 'Dotted',
  'Download': 'Lataa',
  'Downloading information': 'Downloading information',
  'Drawing Mode': 'Piirtotila',
  'Dynamic Drawing': 'Dynamic Drawing',
  'e-Book List': 'e-Book List',
  'e-Books': 'e-Books',
  'Edge': 'Edge',
  'Edge Shape': 'Edge Shape',
  'Edit': 'Muokkaa',
  'Edit(s) has been made.': 'Edit(s) has been made.',
  'Do you want to save edit(s)?': 'Do you want to save edit(s)?',
  'Edit Flock': 'Edit Flock',
  'Edit Memo': 'Edit Memo',
  'Edit Style': 'Edit Style',
  'Editable Mode': 'Editable Mode',
  'Editing': 'Muokkaus',
  'ELLIPSE': 'Ellipsi',
  'Erase': 'Erase',
  'Failed': 'Epäonnistui',
  'File Deleted': 'File Deleted',
  'File Upload': 'Tiedoston lataus',
  'Filter': 'Suodatin',
  'Filter Association': 'Filter Association',
  'Filter Topic': 'Filter Topic',
  'Find': 'Etsi',
  'Fixation': 'Fixation',
  'Flock': 'Flock',
  'Font': 'Fontti',
  'Force All Fixed': 'Force All Fixed',
  'Forgot Password?': 'Forgot Password?',
  'Free Mode': 'Vapaa tila',
  'Get Selected Content Style': 'Get Selected Content Style',
  'Get Selected Edge Style': 'Get Selected Edge Style',
  'Get Style of Selected Item': 'Get Style of Selected Item',
  'Go to': 'Go to',
  'Green Memo': 'Green Memo',
  'Group': 'Ryhmä',
  'Height': 'Korkeus',
  'Hidden': 'Piilotettu',
  'Hide': 'Piilota',
  'Hide All': 'Piilota kaikki',
  'Hide Memo': 'Hide Memo',
  'Hide Names': 'Hide Names',
  'Horizontal Axis': 'Horizontal Axis',
  'Horizontal Equal': 'Horizontal Equal',
  'In case you cannot load iframe contents': 'In case you cannot load iframe contents',
  'Introduction': 'Johdanto',
  'item(s) listed below': 'item(s) listed below',
  'Join': 'Join',
  'Keyword': 'Avainsana',
  'Label': 'Tunniste',
  'Layout Topics': 'Layout Topics',
  'Leave': 'Poistu',
  'List': 'Luettelo',
  'List of Notebooks': 'List of Notebooks',
  'Load': 'Lataa',
  'Loading information': 'Loading information',
  'Local editing mode': 'Local editing mode',
  'Login': 'Kirjaudu sisään',
  'LOGIN FAILED': 'LOGIN FAILED',
  'Logout': 'Kirjaudu ulos',
  'maximum size is': 'maximum size is',
  'members': 'members',
  'Memo': 'Muistio',
  'Merge': 'Yhdistä',
  'Miniature': 'Pienoiskuva',
  'Miniature Canvas': 'Miniature Canvas',
  'minimum size is': 'minimum size is',
  'Model': 'Model',
  'More': 'More',
  'Multiple Lines': 'Multiple Lines',
  'Name': 'Nimi',
  'New': 'Uusi',
  'New Axis': 'New Axis',
  'New Child Topic': 'New Child Topic',
  'New Citation': 'New Citation',
  'New Content': 'New Content',
  'Add Resource': 'Add Resource',
  'addMemo': 'Lisää muistio',
  'addSimpleMemo': 'Lisää muistio',
  'Add Memo': 'Lisää muistio',
  'New Flock': 'New Flock',
  'New Note': 'Uusi muistikirja',
  'New Page': 'Uusi sivu',
  'New Topic': 'Uusi aihe',
  'Not Found.': 'Not Found.',
  'Not Owner': 'Not Owner',
  'Note': 'Huomautus',
  'Notebook': 'Muistikirja',
  'Notebook name': 'Notebook name',
  'Notebook saved in cloud as': 'Notebook saved in cloud as',
  'Notice': 'Notice',
  'ELLIPAE': 'Ellipsi',
  'Open': 'Avaa',
  'Overwrite': 'Korvaa',
  'Page Name': 'Sivun nimi',
  'Pages': 'Sivut',
  'Password': 'Salasana',
  'Paste': 'Liitä',
  'Pause': 'Tauko',
  'Pink Memo': 'Pink Memo',
  'Play': 'Toista',
  'Please log in.': 'Kirjaudu sisään.',
  'Please save': 'Tallenna',
  'please wait': 'please wait',
  'Post Page to Chat': 'Post Page to Chat',
  'Post This Page': 'Post This Page',
  'Presentation': 'Presentation',
  'Prev': 'Prev.',
  'Private': 'Yksityinen',
  'Project': 'Project',
  'Public': 'Julkinen',
  'PUBLIC Notebooks': 'PUBLIC Notebooks',
  'Radius': 'Radius',
  'Randomize Layout': 'Randomize Layout',
  'RECTANGLE': 'Suorakulmio',
  'Redo': 'Tee uudelleen',
  'Reference': 'Reference',
  'Reflesh Chat Nodes': 'Refresh Chat Nodes',
  'Refresh': 'Päivitä',
  'Registered Site': 'Registered Site',
  'Release All Fixed': 'Release All Fixed',
  'Relevant Page': 'Relevant Page',
  'Reload': 'Lataa uudelleen',
  'Reset View': 'Palauta näkymä',
  'Reverse': 'Reverse',
  'RHOMBUS': 'Vinoneliö',
  'Role': 'Role',
  'Root': 'Root',
  'ROUNDED': 'Pyöristetyt kulmat',
  'SAMBUICHI PEs Office': 'SAMBUICHI PEs Office',
  'Save': 'Tallenna',
  'Save As': 'Tallenna nimellä',
  'Save New': 'Save New',
  'Save Notebook': 'Tallenna muistikirja',
  'Scatter': 'Scatter',
  'Scope': 'Scope',
  'Screenshot': 'Screenshot',
  'Search': 'Hae',
  'Search Filter': 'Hakusuodatin',
  'Search occurrence for the given (sub)string.': 'Search occurrence for the given (sub)string.',
  'Search the note for the given (sub)string.': 'Search the notebook for the given (sub)string.',
  'Search topic for the given (sub)string.': 'Search topic for the given (sub)string.',
  'Select': 'Valitse',
  'Select All': 'Valitse kaikki',
  'Select Content': 'Select Content',
  'Select Topic': 'Select Topic',
  'separated with spaces': 'separated with spaces',
  'Setting Options': 'Asetukset',
  'Shape': 'Muoto',
  'Short Cuts': 'Short Cuts',
  'Shortcut Keys': 'Shortcut Keys',
  'Show': 'Näytä',
  'Show All': 'Näytä kaikki',
  'Size': 'Koko',
  'Solid': 'Solid',
  'Start': 'Alku',
  'Static Drawing': 'Static Drawing',
  'Straight': 'Suora',
  'Subwindow': 'Subwindow',
  'Table': 'Taulukko',
  'Text': 'Teksti',
  'Text C.': 'Tekstin väri',
  'Text Color': 'Tekstin väri',
  'Text File': 'Text File',
  'The notebook was deleted successfully.': 'The notebook was deleted successfully.',
  'The selected notebook could not be deleted from the cloud service!': 'The selected notebook could not be deleted from the cloud service!',
  'The selected notebook could not be loaded from the cloud service!': 'The selected notebook could not be loaded from the cloud service!',
  'This is the Navigation Window.': 'This is the Navigation Window.\\nIt will always show the whole notebook\\nwith the current viewport shown by\\na red outline. Click to\\nmove the viewport.',
  'THUMBNAIL': 'Pikkukuva',
  'Timemachine': 'Timemachine',
  'Toggle': 'Toggle',
  'Toggle Anchor': 'Toggle Anchor',
  'Toggle Chat': 'Toggle Chat',
  'Toggle Fix': 'Toggle Fix',
  'Toggle Search': 'Toggle search',
  'Topic': 'Aihe',
  'Topic Categoly': 'Aiheluokka',
  'Topics': 'Aiheet',
  'TRIANGLE': 'Kolmio',
  'Tree': 'Puu',
  'Try again after logging in': 'Yritä uudelleen kirjautumisen jälkeen',
  'Tutorial': 'Ohje',
  'Un/Directed': 'Un/Directed',
  'undefined': 'undefined',
  'Undirected Bloom': 'Undirected Bloom',
  'Undo': 'Kumoa',
  'Upload': 'Lähetä',
  'Upload File': 'Lähetä tiedosto',
  'Upload Model ': 'Upload Model',
  'Upload Pdf Annotations': 'Upload Pdf Annotations',
  'Uploaded': 'Uploaded',
  'URL': 'URL',
  'User ID': 'Käyttäjätunnus',
  'User Name': 'Käyttäjänimi',
  'Vertical Axis': 'Pystyakseli',
  'Vertical Equal': 'Tasaa pystysuunnassa',
  'View': 'Näkymä',
  'View Notebook XML': 'View Notebook XML',
  'Visible': 'Näkyvä',
  'Webcat Plus': 'Webcat Plus',
  'White Memo': 'Valkoinen muistio',
  'Width': 'Leveys',
  'World Encyclopedia': 'Maailman tietosanakirja',
  'WuWei & PDF Annotation': 'WuWei & PDF Annotation',
  'WuWei Manual': 'WuWei-käyttöohje',
  'WuWei Tutorial': 'WuWei-opastus',
  'You are logged in as': 'Kirjautunut käyttäjänä',
  'You may try to tap SOURCE link to view contents directly.': 'You may try to tap SOURCE link to view contents directly.',
  'You need to log in before saving. Try to save again after logging in!': 'You need to log in before saving. Try to save again after logging in!',
  'You need to log in to reach your private notebooks': 'You need to log in to reach your private notebooks',
  'You need to log in to use notebooks': 'You need to log in to use notebooks',
  'Your PRIVATE Notebooks': 'Yksityiset muistikirjasi',
  'Zoom': 'Zoom',
  'Create a personal content collection and annotate it.': 'Create a personal content collection and annotate it.',
  'Visual notes will help you organize your thoughts.': 'Visual notes will help you organize your thoughts.'
};
