/**
 * wuwei.nls.JA.js
 * JA translation map
 *
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 * Copyright (c) 2013-2020,2026 SAMBUICHI, Nobuyuki
 * (Sambuichi Professional Engineers Office)
 **/
wuwei.nls.JA = {
  'Publish': '公開',
  'Align': '整列',
  'Define / Ungroup': 'グループ定義/解除',
  'Other': 'その他',
  'Discard': '破棄',
  'Discard current note without saving?': '現在編集中のノートを保存せずに破棄しますか？',
  'Discarded current note': '編集中のノートを破棄しました',
  'Published': '公開しました',
  'Public URL': '公開URL',
  'Open in new tab': '新規タブで開く',
  'Copy URL': 'URLをコピー',
  'Copied': 'コピーしました',
  'Published note is view-only. Editing, saving, and downloading are disabled.': '公開URLで開いたノートは閲覧専用です。編集、保存、ダウンロードはできません。',
  'Disabled': '無効',
  'Download note file': 'ノートファイルをダウンロード',
  'Upload note file': 'ノートファイルをアップロード',
  'Imported note file': 'ノートファイルを読み込みました',
  'Add Page': 'ページ追加',
  'Select a page and edit its name.': 'ページを選択して名称を編集します。',
  'Select a page to copy.': 'コピーするページを選択します。',
  'Select a page to open, edit, copy, or delete.': 'ページを選択して開く、名称編集、コピー、削除を実行します。',
  'WuWei Home': 'WuWeiホーム',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'アップロード済みコンテンツや登録済みウェブページを一覧し、コメントを付けて選択したコンテンツからノート編集を始めます。',
  'Search content': 'コンテンツ検索',
  'Calendar': 'カレンダー',
  'Commands': 'コマンド',
  'Comment to capture your viewpoint before opening a note.': 'ノートを開く前に、まずコメントで観点や着眼点を残せます。',
  'Content gallery': 'コンテンツギャラリー',
  'Add to note': 'ノートに追加',
  'Start date': '開始日',
  'End date': '終了日',
  'Range target': '範囲対象',
  'All content in range': '範囲内のすべて',
  'Selected content in range': '範囲内の選択コンテンツ',
  'Search scope': '検索範囲',
  'Current period': '現在の表示期間',
  'All registered content': '登録済みコンテンツすべて',
  'Apply': '適用',
  'Sun': '日',
  'Mon': '月',
  'Tue': '火',
  'Wed': '水',
  'Thu': '木',
  'Fri': '金',
  'Sat': '土',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': '選択したコンテンツから新規ノートを作成しますか？現在のノートの未保存の変更は破棄されます。',
  'Selected content': '選択中のコンテンツ',
  'Open note': 'ノートを開く',
  'New note': '新規ノート',
  'No comment yet': 'コメントはまだありません',
  'Click a card to preview the content and start working.': 'カードをクリックして内容を確認し、作業を始めてください。',
  'No content in selected period': '選択した期間にコンテンツがありません',
  'Upload content or choose another date from the calendar.': 'コンテンツをアップロードするか、カレンダーで別の日付を選択してください。',
  'Selected day': '選択日',
  'Month': '月',
  'Showing': '表示範囲',
  'Date': '日付',
  'Type': '種別',
  'Title': 'タイトル',
  'Failed to save comment': 'コメントを保存できませんでした',
  'Format': '形式',
  'Saved': '保存しました',
  'This site refused iframe preview.': 'このサイトは iframe での表示を拒否しました。',
  'Delete this timeline segment?': 'このタイムライン区間を削除しますか？',
  'OpenPlayer': 'プレイヤーで開く',
  'Create timeline axis': 'タイムライン軸を作成',
  'Axis properties': '軸プロパティ',
  'Add segment from player': 'プレイヤーからセグメント追加',
  'Segment properties': 'セグメントプロパティ',
  'Edit segment from player': 'プレイヤーからセグメント編集',
  'Delete segment': 'セグメント削除',
  'Info Timeline': 'タイムライン情報',
  'SelectAll': 'すべて選択',
  'Show All Memo': 'すべてのメモを表示',
  'Hide All Memo': 'すべてのメモを隠す',
  'Note Page': 'ページ情報',
  'Select shape': '形を選択',
  'Select font size': 'フォントサイズ選択',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'iframe preview では現在/再生位置の取得は行わず、開始/終了時刻の保存と Open player を利用します。',
  'Timeline axis': 'タイムライン軸',
  'Media': '映像',
  'Direction': '方向',
  'horizontal': '水平方向',
  'vertical': '垂直方向',
  'Media length': '映像長',
  'Default play duration': '既定再生秒数',
  'Axis length': '軸長',
  'Axis width': '軸幅',
  'Axis color': '軸色',
  'Timeline segment': 'タイムライン区間',
  'Video preview': '映像確認',
  'Set current time to start': '→開始時間',
  'Set current time to end': '→終了時間',
  'Create thumbnail': '→サムネ作成',
  'Start time': '開始時間',
  'End time': '終了時間',
  'or': 'または',
  'Play duration': '再生秒数',
  'info': '情報',
  'Background Color': '背景色',
  'Length': '長さ',
  'Segments': '区間数',
  'Default': '既定値',
  'End': '終了',
  'Image': '画像',
  'Video': '動画',
  'Audio': '音声',
  'Apply to group': 'グループに一括適用',
  'Media type': 'メディア種別',
  'Timeline': 'タイムライン',
  'Document': '文書',
  'Duration': '再生時間',
  'Auto': '自動',
  'jump start': '開始位置へ移動',
  'jump end': '終了位置へ移動',
  'set start here': 'ここを開始位置に',
  'set end here': 'ここを終了位置に',
  'apply': '適用',
  'Define simple group': '単純グループを定義',
  'Define horizontal axis group': '水平軸グループを定義',
  'Define vertical axis group': '垂直軸グループを定義',
  'Ungroup': 'グループ解除',
  'Axis': '軸',
  'TimeLine': 'タイムライン',
  'Create axis group': '軸グループを作成',
  'Add time point': '時点を追加',
  'Edit time point': '時点を編集',
  'Delete time point': '時点を削除',
  'Text position': '文字位置',
  'CENTER': '中央',
  'TOP': '上',
  'TOP_RIGHT': '右上',
  'RIGHT': '右',
  'BOTTOM_RIGHT': '右下',
  'BOTTOM': '下',
  'BOTTOM_LEFT': '左下',
  'LEFT': '左',
  'TOP_LEFT': '左上',
  'Click the Marker Icon': 'マーカーアイコンをクリック',
  'HOLLOW-CIRCLE': '白抜き円',
  'LINE-ARROW': '線矢印',
  'HOLLOW-ARROW': '白抜き矢印',
  'ARROW': '矢印',
  'HOLLOW-RHOMBUS': '白抜き菱形',
  'Chat record': 'チャット履歴',
  'Nothing to edit': '編集するものはありません',
  'Archives': 'アーカイブ',
  'HORIZONTAL2': '横向き',
  'VERTICAL2': '縦向き',
  'Web page': 'ウェブページ',
  'Total items': '総数',
  'Workbench': '作業台',
  'Source': 'ソース',
  'Content': 'コンテンツ',
  '_Content': '内容',
  'Assignment': '課題',
  'Deselect': '選択解除',
  'Summary': '概要',
  'Student': '学生',
  'Faculty': '教師',
  'List of Pages': 'ページ一覧',
  'Loading notebook': 'ノートを読み込んでいます',
  'Showing list': '一覧を表示中',
  'Annotate': '注釈',
  'Clipboard': 'クリップボード',
  'Row': '行',
  'Column': '欄',
  'Value': '値',
  'Table Header': 'ヘッダー',
  'New Table': '新規表',
  'Add Table': '表追加',
  'Newsletter': 'ニュースレター',
  'Questions? Go ahead.': 'ご不明な点がありますか？お問い合わせください。',
  'Send': '送信',
  'Message': 'メッセージ',
  'Subject': '課題', // kcua,
  'Email': '電子メールアドレス',
  'Contact': '連絡先',
  'ERROR LOGIN FAILED': 'エラー：ログインに失敗しました',
  'ERROR NOT LOGGED IN': 'エラー：ログインしていません',
  'ERROR NOTE DIR NOT DEFINED': 'エラー：ノートのディレクトリが定義されていません',
  'ERROR RESOURCE DIR NOT DEFINED': 'エラー：リソースのディレクトリが定義されていません',
  'ERROR EMPTY KEYWORD': 'エラー：キーワードが空です',
  'SUCCESS NOTE REMOVED': '成功：ノートを削除しました',
  'SUCCESS RESOURCE REMOVED': '成功：リソースが削除されました',
  'SUCCESS RESOURCE UPDATED': '成功：リソースが更新されました',
  'ERROR NOTE NOT REMOVED': 'エラー：ノートは削除されません',
  'ERROR RESOURCE NOT UPDATED': 'エラー：リソースが更新されていません',
  'ERROR RESOURCE NOT REMOVED': 'エラー：リソースが削除されていません',
  'Bring forward': '前面に移動',
  'Send backward': '背面に移動',
  'You are logged in.': 'ログインしています。',
  'You are logged out.': 'ログアウトしています。',
  'Do you want to log out?': 'ログアウトしますか？',
  'Align Top': '上に揃える',
  'Align Bottom': '下に揃える',
  'Align Right': '右に揃える',
  'Align Left': '左に揃える',
  'Click to open window': 'クリックしてウィンドウを開く',
  'Comment': '解説',
  'Background': '背景',
  'Sourceposition': '始点位置',
  'Targetposition': '終点位置',
  'Info': '情報',
  'OpenWindow': '新しいウィンドウで開く',
  'CloseWindow': 'ウィンドウを閉じる',
  'OpenNewTab': '新しいタブで開く',
  'NORMAL': '通常',
  'HORIZONTAL': '横向き',
  'VERTICAL': '縦向き',
  'SOLID': '実線',
  'DOTTED': '点線',
  'DASHED': '破線',
  'LONG-DASHED': '長破線',
  'Stroke': '引き方',
  'erase': '削除',
  'bloom': '関連を展開',
  'wilt': '関連を収束',
  'Bloom': '関連を展開',
  'Wilt': '関連を収束',
  'move': '移動',
  'drag': '移動',
  'and': ' 及び',
  '-': '-',
  '+': '+',
  'Abbreviation': '省略',
  'About': 'ヘルプ',
  'addContent': 'コンテンツ追加',
  'addSimpleContent': 'コンテンツ追加',
  'Add Content': 'コンテンツ追加',
  'Add New Topic with Style of This Palette': 'パレットのスタイルでトピックを追加',
  'addTopic': 'トピック追加',
  'addSimpleTopic': 'トピック追加',
  'Add Topic': 'トピック追加',
  'Adjust Size': '可変サイズ',
  'Align Horizontal': '水平に揃える',
  'Align Vertical': '垂直に揃える',
  'All': '全て',
  'Amoeba': 'アメーバ',
  'Anchor': '固定',
  'Anchor Mode': '配置：固定モード',
  'Angle': '角度',
  'Anonymous Model': '匿名ノート',
  'Anonyous': '匿名化',
  'Any unsaved changes will be lost': '保存していない変更内容は失われます。',
  'Are you absolutely sure you want to leave': 'このページを閉じてもよろしいですか？',
  'Are you sure you want to delete the following': '次に示す要素を削除してもよろしいですか',
  'Are you sure you want to delete this notebook?': '削除してもよろしいですか？',
  'Are you sure you want to merge': '次のトピックをマージしてもよろしいですか？　',
  'Arrow Head': '矢印あり',
  'Associatins': '関連線の形',
  'Association': '関連線',
  'Association Role': '関連ロール',
  'AUGMENT': '追加',
  'Blank': '白紙',
  'Bloom All Direction': '関連線の方向によらず全て展開',
  'Bloom by Direction': '関連線の方向で展開を制限',
  'Blue Memo': '青い付箋紙',
  'Cancel': '取消',
  'Close': '閉じる',
  'Change': '変更',
  'Change Password': 'パスワード変更',
  'Chat Mode': '共同作業モード',
  'CIRCLE': '円',
  'Citation': '引用',
  'Class': '分類',
  'Clear': '消去',
  'Clear Chat Nodes': '共同作業の内容を消去しています。',
  'Clear Screen': '画面消去',
  'Clear Selection': '選択解除',
  'Clone': '複製',
  'Cloud mode editing': 'クラウドモードで編集中',
  'Collabolation': '共同作業',
  'Color': '色',
  'COMMIT': '実行',
  'connect': '繋ぐ',
  'Resource': 'コンテンツ',
  'CONTENTS URL': 'コンテンツURL',
  'Control Buttons': 'コントロールボタン',
  'Copy': 'コピー',
  'Copy & Paste': 'コピー＆ペースト',
  'Copyright': '著作権',
  'Create & Edit': '作成と編集',
  'Create Account': 'ユーザ登録',
  'Create New': '新しく作成',
  'Creator': '作者',
  'Curve': 'やわらかい関連線',
  'Curve/Line': 'やわらかい/真直ぐな関連線',
  'Cut': 'カット',
  'Dashed': '破線',
  'Long dashed': '長破線',
  'Date Picker': '日付指定',
  'defined by': '作',
  'Delete': '削除',
  'Deleting information': '削除しています。',
  'Dialog': '対話',
  'Diameter': '直径',
  'Do you want create new note?': '新規ノートを作成しますか？',
  'Dotted': '点線',
  'Download': 'ダウンロード',
  'Downloading information': 'ダウンロードしています。',
  'Drawing Mode': '描画モード',
  'Dynamic Drawing': '動的描画',
  'e-Book List': '書籍一覧',
  'e-Books': '電子書庫',
  'Edge': '関連線',
  'Edge Shape': '線種',
  'Edit': '編集',
  'Edit(s) has been made.': '編集完了',
  'Do you want to save edit(s)?': '変更内容を保存しますか？',
  'Edit Flock': 'グループ編集',
  'Edit Memo': '付箋紙編集',
  'Edit Style': 'スタイル編集',
  'Editable Mode': '編集モード',
  'Editing': '編集中',
  'ELLIPSE': '楕円',
  'Erase': '削除',
  'Failed': 'アップロード失敗',
  'File Deleted': 'ファイル削除',
  'File Upload': 'ファイル　アップロード',
  'Filter': '絞込表示',
  'Filter Association': '関連線絞込',
  'Filter Topic': 'トピック絞込',
  'Find': '見つける',
  'Fixation': '再配置',
  'Flock': 'グループ',
  'Font': 'フォント',
  'Force All Fixed': '全てを固定',
  'Forgot Password?': 'パスワードをお忘れですか？',
  'Free Mode': '配置：遊動モード',
  'Get Selected Content Style': '選択したコンテンツのスタイル取得',
  'Get Selected Edge Style': '選択した線のスタイル取得',
  'Get Style of Selected Item': '選択した対象のスタイル取得',
  'Go to': '移動',
  'Green Memo': '緑の付箋紙',
  'Group': '分類',//kcua,
  'Height': '高さ',
  'Hidden': '非表示',
  'Hide': '非表示',
  'Hide All': '全て非表示',
  'Hide Memo': '付箋紙非表示',
  'Hide Names': '作成者名非表示',
  'Horizontal Axis': '水平軸作成',
  'Horizontal Equal': '左右に整列',
  'Distribute PageMarkers': 'ページマーカーを均等間隔に並べる',
  'In case you cannot load iframe contents': 'iframeの内容を表示できないときには',
  'Introduction': '説明',
  'item(s) listed below': 'トピック（コンテンツ）(下に示します)',
  'Join': 'グループに加える',
  'Keyword': 'キーワード',
  'Label': 'ラベル',
  'Layout Topics': 'トピック配置',
  'Leave': 'グループから外す',
  'List': '一覧',
  'List of Notebooks': 'ノート一覧',
  'Load': 'ロード',
  'Loading information': 'ロードしています。',
  'Local editing mode': 'オフライン編集モード',
  'Login': 'ログイン',
  'LOGIN FAILED': 'ログインできませんでした',
  'Logout': 'ログアウト',
  'maximum size is': '画像の最大サイズは',
  'members': 'グループメンバ',
  'Memo': '付箋紙',
  'Merge': 'マージ',
  'Miniature': '縮小図',
  'Miniature Canvas': '縮図　表示/非表示',
  'minimum size is': '画像の最小サイズは',
  'Model': 'モデル',
  'More': '次',
  'Multiple Lines': '複数行',
  'Name': '名前',
  'New': '新規',
  'New Axis': '新しい軸',
  'New Child Topic': '新規子トピック',
  'New Citation': '新規引用',
  'New Content': '新規コンテンツ',
  'Add Resource': 'コンテンツ追加',
  'addMemo': '付箋紙追加',
  'addSimpleMemo': '付箋紙追加',
  'Add Memo': '付箋紙追加',
  'New Flock': '新規グループ',
  'New Note': '新しく作成',
  'New Page': 'ページ作成',
  'New Topic': '新規トピック',
  'Not Found.': '見つかりませんでした',
  'Not Owner': '作者ではありません',
  'Note': '注記',
  'Notebook': 'ノート',
  'Notebook name': 'ノート名',
  'Notebook saved in cloud as': 'ノートをクラウドに保存しました：',
  'Notice': 'お知らせ',
  'ELLIPAE': '楕円',
  'Open': '開く',
  'Overwrite': '上書き保存',
  'Page Name': '名前',
  'Pages': 'ページ操作',
  'Password': 'パスワード',
  'Paste': 'ペースト',
  'Pause': '停止',
  'Pink Memo': 'ピンクの付箋紙',
  'Play': '遊動',
  'Please log in.': 'ログインしてください',
  'Please save': '保存してください',
  'please wait': 'そのままでお待ちください。',
  'Post Page to Chat': '共同作業の内容を登録しています。',
  'Post This Page': 'ページ公開',
  'Presentation': 'プレゼンテーション',
  'Prev': '前',
  'Private': '非公開',
  'Project': 'プロジェクト',
  'Public': '公開',
  'PUBLIC Notebooks': '公開ノート一覧',
  'Radius': '半径',
  'Randomize Layout': 'ランダム配置',
  'RECTANGLE': '四角形',
  'Redo': 'やり直し',
  'Reference': '出典',
  'Reflesh Chat Nodes': '共同作業の内容を更新しています。',
  'Refresh': '更新',
  'Registered Site': '登録したサイト',
  'Release All Fixed': '全てを解放',
  'Relevant Page': '該当ページ',
  'Reload': 'ページを再読込（更新）',
  'Reset View': '中央に配置',
  'Reverse': '逆方向',
  'RHOMBUS': '菱形',
  'Role': 'ロール',
  'Root': '単独表示',
  'ROUNDED': '角丸',
  'SAMBUICHI PEs Office': '三分一技術士事務所',
  'Save': '保存',
  'Save As': '別名保存',
  'Save New': '新規登録',
  'Save Notebook': '保存',
  'Scatter': 'グループ解除',
  'Scope': 'スコープ',
  'Screenshot': '画面を印刷',
  'Search': '検索',
  'Search Filter': ' 検索文字列',
  'Search occurrence for the given (sub)string.': '検索文字列を含むコンテンツを検索します',
  'Search the note for the given (sub)string.': '検索文字列を含んだトピック候補に絞り込みます',
  'Search topic for the given (sub)string.': '検索文字列を含むトピックを検索します',
  'Select': '選択',
  'Select All': 'すべて選択',
  'Select Content': 'コンテンツを選択',
  'Select Topic': 'トピックを選択',
  'separated with spaces': '空白で分割',
  'Setting Options': 'オプション設定',
  'Shape': '形',
  'Short Cuts': 'ショートカット',
  'Shortcut Keys': 'ショートカット表示',
  'Show': '表示',
  'Show All': '全て表示',
  'Size': 'サイズ',
  'Solid': '実線',
  'Start': '開始',
  'Static Drawing': '静的描画',
  'Straight': '真直ぐな関連線',
  'Subwindow': '実際のコンテンツ',
  'Table': '表',
  'Text': '文字',
  'Text C.': '文字色',
  'Text Color': '文字色',
  'Text File': 'テキスト　ファイル',
  'The notebook was deleted successfully.': 'ノートを削除しました。',
  'The selected notebook could not be deleted from the cloud service!': 'ノートは、クラウドから削除できませんでした！',
  'The selected notebook could not be loaded from the cloud service!': 'ノートをクラウドサービスからロードできませんでした',
  'This is the Navigation Window.': 'これは、画面移動用のウィンドウです。ここには、いつもノートの全体が表示されます。\n今見えている画面の範囲が赤い枠線で表示され、クリックするとそこを画面の中央に移動します。',
  'THUMBNAIL': '縮小画像',
  'Timemachine': '更新履歴',
  'Toggle': '表示切り替え',
  'Toggle Anchor': '固定/遊動',
  'Toggle Chat': '開始・終了',
  'Toggle Fix': '固定/遊動',
  'Toggle Search': '検索　表示/非表示',
  'Topic': 'トピック',
  'Topic Categoly': 'カテゴリー',
  'Topics': 'トピック',
  'TRIANGLE': '三角形',
  'Tree': '階層',
  'Try again after logging in': 'ログインした後で、再度実行してください。',
  'Tutorial': 'チュートリアル',
  'Un/Directed': '方向で展開を制限する/しない',
  'undefined': '未定義',
  'Undirected Bloom': '無方向展開',
  'Undo': '元に戻す',
  'Upload': 'アップロード',
  'Upload File': 'ファイルアップロード',
  'Upload Model ': 'アップロード',
  'Upload Pdf Annotations': 'Pdf注釈アップロード',
  'Uploaded': 'アップロード完了',
  'URL': 'URL',
  'User ID': 'ユーザID',
  'User Name': '作成者名表示',
  'Vertical Axis': '垂直軸作成',
  'Vertical Equal': '上下に整列',
  'View': 'プレゼンテーション',
  'View Notebook XML': 'ノートのXML表示',
  'Visible': '表示',
  'Webcat Plus': '連想検索',
  'White Memo': '白い付箋紙',
  'Width': '幅',
  'World Encyclopedia': '世界大百科事典',
  'WuWei & PDF Annotation': 'WuWei&PDF注釈',
  'WuWei Manual': 'WuWei操作マニュアル',
  'WuWei Tutorial': 'WuWei操作説明',
  'You are logged in as': 'ようこそ',
  'You may try to tap SOURCE link to view contents directly.': '内容が表示されないときは、SOUCEのリンクを直接クリックしてください。',
  'You need to log in before saving. Try to save again after logging in!': 'ノートを保存するにはログインしている必要があります。ログインした後に再度、保存してください！',
  'You need to log in to reach your private notebooks': '非公開ノートを使用するにはログインしてください。',
  'You need to log in to use notebooks': 'ノートを使用するにはログインしてください。',
  'Your PRIVATE Notebooks': '非公開ノート一覧',
  'Zoom': 'ズーム',
  'Create a personal content collection and annotate it.': 'コンテンツコレクションを作成し注釈を付けます。',
  'Visual notes will help you organize your thoughts.': '無為ノートは、考えを整理する助けとなります。',
  'Add table of contents': '目次を追加',
  'Table of contents was added.': '目次を追加しました。',
  'Contents module is not available.': 'Contentsモジュールを利用できません。',
  'Failed to add table of contents.': '目次の追加に失敗しました。',
  'Select colour': '色選択',
  'HTML PageMarker must specify anchorHref starting with #.': 'HTML PageMarkerには # で始まる anchorHref を指定してください。',
  'Page number': 'ページ番号',
  'Apply to group members': 'グループメンバーへ一括適用',
  'This preview cannot create a thumbnail. Please try an HTML5 video such as mp4.': 'この preview からはサムネを作成できません。mp4 などの HTML5 動画で試してください。',
  'This video format is not supported in embedded preview.': 'この映像形式は埋め込み preview に未対応です。',
  'Open source video': '元の映像を開く',
  'start / end cannot be deleted.': 'start / end は削除できません。',
  'Delete this time point?': 'この時刻点を削除しますか？',
  'Please use Open player / Open in new tab.': 'Open player / Open in new tab を使用してください。',
  'No download URL.': 'ダウンロードURLがありません',
  'Upload File does not accept compressed files such as zip or tar.': 'Upload File では zip / tar などの圧縮ファイルは対象外です。',
  'To restore a note ZIP, use the note upload function.': 'ノート ZIP を復元する場合は、ノートのアップロード機能を使用してください。',
  'Select one contents target content before creating contents.': 'contents 対象のコンテンツを 1 件選択してから contents を作成してください。',
  'Select one base video before creating timeline.': '基準映像を 1 件選択してから timeline を作成してください。',
  'sambuichi.jp top page sample. The selected preview is displayed in an iframe.': '一般のホームページ例。selected preview は iframe で表示する。',
  'External PDF sample. The selected preview is displayed as a PDF iframe.': '外部 PDF 例。selected preview は PDF を iframe で表示する。',
  'IPA PDF sample. The selected preview is displayed in the PDF view.': 'IPA の PDF 例。selected preview は PDF ビューで表示する。',
  'General HTML page sample. The selected preview is displayed in an iframe.': '一般の HTML ページ例。selected preview は iframe で表示する。',
  'Vimeo video sample. The selected preview uses a Vimeo embedded iframe.': 'Vimeo 動画例。selected preview は Vimeo 埋め込み iframe を使用する。',
  'Image viewer sample. The selected preview is displayed using an img element.': 'image viewer の確認用。selected preview は img 要素で表示する。',
  'Thumbnail viewer sample. The selected preview displays only the thumbnail image.': 'thumbnail viewer の確認用。selected preview は thumbnail 画像のみ表示する。',

  '{name} joined the room.': '{name}さんが入室しました。',
  '{name} loaded the note.': '{name}さん　ノートを読み込みました',
  '{name} created': '{name}が作成',
  '{name} modified': '{name}が変更',
  '{name} deleted': '{name}が削除',
  'Target': '対象',

  'Add Axis': '軸追加',
  'Add Entry': 'ページ追加',
  'Add Segment': 'セグメント追加',
  'Edit properties': '属性編集',
  'Edit style': 'スタイル編集',

  'Standard colours': '標準色',
  'Folded corner': '折り返し角',
  'Apply to all group members': 'グループに一括適用',


  'Content kind': 'コンテンツ種別',

  'Link condition': 'リンク条件',

  'Show matching items': '一致するものだけ表示',

  'Hide matching items': '一致するものを非表示',

  'Show all page data': '対象ページの全データを表示',

  'matches': '件',

  'Enter search string': '検索文字列を入力',

  'Office document': 'Office文書',
  'Physical page 1 corresponds to': '物理1ページ目の表示ページ番号',
  'Page offset': 'ページオフセット',
  'Page max': 'ページ最大値',
  'Page min': 'ページ最小値',

  'Page number is below the valid range.': 'ページ番号が有効範囲より小さい値です。',
  'Page number is above the valid range.': 'ページ番号が有効範囲より大きい値です。',
  'Corrected to minimum page number': '最小ページ番号に修正しました',
  'Corrected to maximum page number': '最大ページ番号に修正しました',

  'Label position': 'ラベル位置',
  'Label align': 'ラベル揃え',
  'Label width': 'ラベル幅',
  'Label lines': 'ラベル行数',
  'Label offset X': 'ラベル水平距離',
  'Label offset Y': 'ラベル垂直距離',
  'Select label position': 'ラベル位置を選択',

  'offset': 'オフセット',
  'max': '最大値',
  'min': '最小値',
  'position': '位置',
  'align': '揃え',
  'width': '幅',
  'lines': '行数',
  'offset X': '水平距離',
  'offset Y': '垂直距離',

  'PageMarkers': 'PageMarker一覧',
  'Anchor href': 'anchor href',
  'Description': '説明',

};
