/**
 * wuwei.nls.KR.js
 * KR translation map
 *
 * Revised against JA baseline on 2026-04-17.
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 **/
wuwei.nls.KR = {
  'Publish': '공개',
  'Align': '정렬',
  'Define / Ungroup': '그룹 정의/해제',
  'Other': '기타',
  'Published': 'Published',
  'Public URL': 'Public URL',
  'Open in new tab': 'Open in new tab',
  'Copy URL': 'Copy URL',
  'Copied': 'Copied',
  'Published note is view-only. Editing, saving, and downloading are disabled.': 'Published note is view-only. Editing, saving, and downloading are disabled.',
  'Disabled': 'Disabled',
  'Download note file': 'Download note file',
  'Upload note file': 'Upload note file',
  'Imported note file': 'Imported note file',
  'Add Page': 'Add Page',
  'Select a page and edit its name.': 'Select a page and edit its name.',
  'Select a page to copy.': 'Select a page to copy.',
  'Select a page to open, edit, copy, or delete.': 'Select a page to open, edit, copy, or delete.',
  'WuWei Home': 'WuWei Home',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.',
  'Search content': 'Search content',
  'Calendar': 'Calendar',
  'Commands': 'Commands',
  'Comment to capture your viewpoint before opening a note.': 'Comment to capture your viewpoint before opening a note.',
  'Content gallery': 'Content gallery',
  'Add to note': 'Add to note',
  'Start date': 'Start date',
  'End date': 'End date',
  'Range target': 'Range target',
  'All content in range': 'All content in range',
  'Selected content in range': 'Selected content in range',
  'Search scope': 'Search scope',
  'Current period': 'Current period',
  'All registered content': 'All registered content',
  'Apply': 'Apply',
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': 'Create a new note from the selected content? Unsaved changes in the current note will be discarded.',
  'Selected content': 'Selected content',
  'Open note': 'Open note',
  'New note': 'New note',
  'No comment yet': 'No comment yet',
  'Click a card to preview the content and start working.': 'Click a card to preview the content and start working.',
  'No content in selected period': 'No content in selected period',
  'Upload content or choose another date from the calendar.': 'Upload content or choose another date from the calendar.',
  'Selected day': 'Selected day',
  'Month': 'Month',
  'Showing': 'Showing',
  'Date': '날짜',
  'Type': '종류',
  'Title': 'Title',
  'Failed to save comment': 'Failed to save comment',
  'Format': 'Format',
  'Saved': 'Saved',
  'This site refused iframe preview.': 'This site refused iframe preview.',
  'Delete this timeline segment?': '이 타임라인 구간을 삭제하시겠습니까?',
  'OpenPlayer': '플레이어로 열기',
  'Create timeline axis': '타임라인 축 만들기',
  'Axis properties': '축 속성',
  'Add segment from player': '플레이어에서 세그먼트 추가',
  'Segment properties': '세그먼트 속성',
  'Edit segment from player': '플레이어에서 세그먼트 편집',
  'Delete segment': '세그먼트 삭제',
  'Info Timeline Segment': '타임라인 정보',
  'SelectAll': '모두 선택',
  'Show All Memo': '모든 메모 표시',
  'Hide All Memo': '모든 메모 숨기기',
  'Note Page': '페이지 정보',
  'Select shape': '도형 선택',
  'Select font size': '글꼴 크기 선택',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'iframe 미리보기에서는 현재/재생 위치를 가져오지 않고, 시작/종료 시간을 저장한 뒤 Open Player를 사용합니다.',
  'Timeline axis': '타임라인 축',
  'Media': '미디어',
  'Direction': '방향',
  'horizontal': '수평',
  'vertical': '수직',
  'Media length': '미디어 길이',
  'Default play duration': '기본 재생 시간',
  'Axis length': '축 길이',
  'Axis width': '축 너비',
  'Axis color': '축 색상',
  'Timeline segment': '타임라인 구간',
  'Video preview': '동영상 미리보기',
  'Set current time to start': '현재 시간을 시작 시간으로 설정',
  'Set current time to end': '현재 시간을 종료 시간으로 설정',
  'Create thumbnail': '썸네일 만들기',
  'Start time': '시작 시간',
  'End time': '종료 시간',
  'or': '또는',
  'Play duration': '재생 시간',
  'info': '정보',
  'Background Color': '배경색',
  'Length': '길이',
  'Segments': '구간 수',
  'Default': '기본값',
  'End': '종료',
  'Image': '이미지',
  'Video': '동영상',
  'Audio': '오디오',
  'Apply to group': '그룹에 적용',
  'Media type': '미디어 종류',
  'Timeline': '타임라인',
  'Document': '문서',
  'Duration': '재생 시간',
  'Auto': '자동',
  'jump start': '시작 위치로 이동',
  'jump end': '종료 위치로 이동',
  'set start here': '여기를 시작 위치로 설정',
  'set end here': '여기를 종료 위치로 설정',
  'apply': '적용',
  'Define simple group': '단순 그룹 정의',
  'Define horizontal axis group': '수평 축 그룹 정의',
  'Define vertical axis group': '수직 축 그룹 정의',
  'Ungroup': '그룹 해제',
  'Axis': '축',
  'TimeLine': '타임라인',
  'Create axis group': '축 그룹 만들기',
  'Add time point': '시점 추가',
  'Edit time point': '시점 편집',
  'Delete time point': '시점 삭제',
  'Text position': '텍스트 위치',
  'CENTER': '가운데',
  'TOP': '상단',
  'TOP_RIGHT': '오른쪽 상단',
  'RIGHT': '오른쪽',
  'BOTTOM_RIGHT': '오른쪽 하단',
  'BOTTOM': '하단',
  'BOTTOM_LEFT': '왼쪽 하단',
  'LEFT': '왼쪽',
  'TOP_LEFT': '왼쪽 상단',
  'Click the Marker Icon': '마커 아이콘을 클릭하십시오',
  'HOLLOW-CIRCLE': '중공 원',
  'LINE-ARROW': '선 화살표',
  'HOLLOW-ARROW': '중공 화살',
  'ARROW': '화살',
  'HOLLOW-RHOMBUS': '중공 마름모',
  'Chat record': '공동작업 기록',
  'Nothing to edit': '편집 할 것이 없습니다',
  'Archives': '아카이브',
  'HORIZONTAL2': '가로',
  'VERTICAL2': '세로',
  'Web page': '웹 페이지',
  'Total items': '총수',
  'Workbench': '작업 공간',
  'Source': '출처',
  'Content': '콘텐츠',
  '_Content': '콘텐츠',
  'Assignment': '과제',
  'Deselect': '선택 취소',
  'Summary': '요약',
  'Student': '학생',
  'Faculty': '교수진',
  'List of Pages': '페이지 목록',
  'Loading notebook': '노트를 불러오는 중',
  'Showing list': '목록 표시 중',
  'Annotate': '주석',
  'Clipboard': '클립 보드',
  'Row': '행',
  'Column': '열',
  'Value': '값',
  'Table Header': '테이블 헤더',
  'New Table': '새로운 테이블',
  'Add Table': '테이블 추가',
  'Newsletter': '뉴스레터',
  'Questions? Go ahead.': '질문이 있으신가요? 문의해 주세요.',
  'Send': '보내기',
  'Message': '메시지',
  'Subject': '제목',
  'Email': '이메일 주소',
  'Contact': '연락처',
  'ERROR LOGIN FAILED': '오류 : 로그인 실패',
  'ERROR NOT LOGGED IN': '오류 : 로그인하지 않았습니다',
  'ERROR NOTE DIR NOT DEFINED': '오류: 노트 디렉터리가 정의되지 않았습니다',
  'ERROR RESOURCE DIR NOT DEFINED': '오류: 리소스 디렉터리가 정의되지 않았습니다',
  'ERROR EMPTY KEYWORD': '오류 : 빈 키워드',
  'SUCCESS NOTE REMOVED': '성공: 노트가 삭제되었습니다',
  'SUCCESS RESOURCE REMOVED': '성공 : 자원 제거',
  'SUCCESS RESOURCE UPDATED': '성공 : 자원 업데이트',
  'ERROR NOTE NOT REMOVED': '오류 : 노트북이 제거되지 않았습니다',
  'ERROR RESOURCE NOT UPDATED': '오류 : 자원이 업데이트되지 않았습니다',
  'ERROR RESOURCE NOT REMOVED': '오류 : 자원이 제거되지 않았습니다',
  'Bring forward': '앞으로 가져오기',
  'Send backward': '뒤로 보내기',
  'You are logged in.': '로그인되었습니다.',
  'You are logged out.': '로그아웃되었습니다.',
  'Do you want to log out?': '로그 아웃 하시겠습니까?',
  'Align Top': '위쪽 정렬',
  'Align Bottom': '아래쪽 정렬',
  'Align Right': '오른쪽 정렬',
  'Align Left': '왼쪽 정렬',
  'Click to open window': '창을 열려면 클릭하십시오',
  'Comment': '설명',
  'Background': '배경',
  'Sourceposition': '소스 위치',
  'Targetposition': '대상 위치',
  'Info': '정보',
  'OpenWindow': '새 창 열기',
  'CloseWindow': '창 닫기',
  'OpenNewTab': '새 탭 열기',
  'NORMAL': '일반',
  'HORIZONTAL': '가로',
  'VERTICAL': '세로',
  'SOLID': '실선',
  'DOTTED': '점선',
  'DASHED': '점선',
  'LONG-DASHED': '긴 파선',
  'Stroke': '선 종류',
  'erase': '지우다',
  'bloom': '열기',
  'wilt': '접기',
  'Bloom': '열기',
  'Wilt': '접기',
  'move': '이동',
  'drag': '이동',
  'and': '및',
  '-': '-',
  '+': '+',
  'Abbreviation': '생략',
  'About': '정보',
  'addContent': '컨텐츠 추가',
  'addSimpleContent': '컨텐츠 추가',
  'Add Content': '컨텐츠 추가',
  'Add New Topic with Style of This Palette': '팔레트 스타일로 토픽 추가',
  'addTopic': '토픽 추가',
  'addSimpleTopic': '토픽 추가',
  'Add Topic': '토픽 추가',
  'Adjust Size': '크기 조정',
  'Align Horizontal': '가로 정렬',
  'Align Vertical': '세로 정렬',
  'All': '모두',
  'Amoeba': '아메바',
  'Anchor': '고정',
  'Anchor Mode': '배치:고정모드',
  'Angle': '각도',
  'Anonymous Model': '익명 모델',
  'Anonyous': '익명화',
  'Any unsaved changes will be lost': '저장하지 않은 변경 내용은 소실됩니다.',
  'Are you absolutely sure you want to leave': '페이지를 닫을까요?',
  'Are you sure you want to delete the following': '이 요소를 삭제해도 될까요?',
  'Are you sure you want to delete this notebook?': '삭제해도 될까요?',
  'Are you sure you want to merge': '이 토픽을 병합하겠습니까?',
  'Arrow Head': '화살표',
  'Associatins': '관련선',
  'Association': '관련선',
  'Association Role': '관련 역할',
  'AUGMENT': '확장',
  'Blank': '백지',
  'Bloom All Direction': '모든 방향으로 펼치기',
  'Bloom by Direction': '방향에 따라 펼치기',
  'Blue Memo': '파란색 메모지',
  'Cancel': '취소',
  'Close': '닫기',
  'Change': '변경',
  'Change Password': '패스워드 변경',
  'Chat Mode': '협업 모드',
  'CIRCLE': '원',
  'Citation': '인용',
  'Class': '분류',
  'Clear': '지우기',
  'Clear Chat Nodes': '공동작업 내용을 삭제합니다',
  'Clear Screen': '화면삭제',
  'Clear Selection': '선택 해제',
  'Clone': '복제',
  'Cloud mode editing': '클라우드 편집 모드',
  'Collabolation': '협업',
  'Color': '색깔',
  'COMMIT': '실행',
  'connect': '연결',
  'Resource': '컨텐츠',
  'CONTENTS URL': '컨텐츠 URL',
  'Control Buttons': '컨트롤 버튼',
  'Copy': '복사',
  'Copy & Paste': '복사/붙여넣기',
  'Copyright': '저작권',
  'Create & Edit': '작성과 편집',
  'Create Account': '사용자 등록',
  'Create New': '새로 만들기',
  'Creator': '작성자',
  'Curve': '부드러운 관련선',
  'Curve/Line': '곡선/직선',
  'Cut': '자르기',
  'Dashed': '파선',
  'Date Picker': '날짜 지정',
  'defined by': '작성자',
  'Delete': '삭제',
  'Deleting information': '삭제 중입니다',
  'Dialog': '대화',
  'Diameter': '직경',
  'Do you want create new note?': '신규 노트를 작성하겠습니까?',
  'Dotted': '점선',
  'Download': '다운로드',
  'Downloading information': '다운로드 중입니다',
  'Drawing Mode': '그리기 모드',
  'Dynamic Drawing': '움직이는 그리기',
  'e-Book List': '서적일람',
  'e-Books': '전자서고',
  'Edge': '관련선',
  'Edge Shape': '선 종류',
  'Edit': '편집',
  'Edit(s) has been made.': '편집이 완료되었습니다',
  'Do you want to save edit(s)?': '수정 사항을 저장 하시겠습니까?',
  'Edit Flock': '그룹 편집',
  'Edit Memo': '메모지 편집',
  'Edit Style': '스타일 편집',
  'Editable Mode': '편집모드',
  'Editing': '편집중',
  'ELLIPSE': '타원',
  'Erase': '삭제',
  'Failed': '업로드 실패',
  'File Deleted': '파일 삭제',
  'File Upload': '파일 업로드',
  'Filter': '필터링 표시',
  'Filter Association': '관련선을 필터링',
  'Filter Topic': '토픽 필터링',
  'Find': '찾기',
  'Fixation': '재배치',
  'Flock': '그룹',
  'Font': '글꼴',
  'Force All Fixed': '모두 고정',
  'Forgot Password?': '패스워드를 잊으셨나요?',
  'Free Mode': '자유 모드',
  'Get Selected Content Style': '선택한 컨텐츠의 스타일 취득하기',
  'Get Selected Edge Style': '선택한 선의 스타일 취득하기',
  'Get Style of Selected Item': '선택한 대상의 스타일 취득하기',
  'Go to': '이동',
  'Green Memo': '녹색 메모지',
  'Group': '그룹',
  'Height': '높이',
  'Hidden': '숨김',
  'Hide': '감추기',
  'Hide All': '모두 감추기',
  'Hide Memo': '메모지 감추기',
  'Hide Names': '작성자명 감추기',
  'Horizontal Axis': '수평축 만들기',
  'Horizontal Equal': '좌우로 정렬',
  'In case you cannot load iframe contents': 'iframe의 내용을 표시할 수 없을 때에는',
  'Introduction': '설명',
  'item(s) listed below': '토픽(컨텐츠)(아래에 보입니다)',
  'Join': '그룹에 추가',
  'Keyword': '키워드',
  'Label': '레이블',
  'Layout Topics': '토픽 배치',
  'Leave': '그룹에서 제외',
  'List': '목록',
  'List of Notebooks': '노트 목록',
  'Load': '불러오기',
  'Loading information': '불러오는 중입니다',
  'Local editing mode': '오프라인 편집모드',
  'Login': '로그인',
  'LOGIN FAILED': '로그인 불가',
  'Logout': '로그아웃',
  'maximum size is': '이미지의 최대 사이즈는',
  'members': '그룹 멤버',
  'Memo': '메모지',
  'Merge': '병합',
  'Miniature': '축소도',
  'Miniature Canvas': '축소도 보이기/감추기',
  'minimum size is': '이미지의 최소 사이즈는',
  'Model': '모델',
  'More': '다음',
  'Multiple Lines': '여러 줄',
  'Name': '이름',
  'New': '새로운',
  'New Axis': '새 축',
  'New Child Topic': '새 하위 토픽',
  'New Citation': '새 인용',
  'New Content': '새 콘텐츠',
  'Add Resource': '신규 컨텐츠',
  'addMemo': '메모지 작성',
  'addSimpleMemo': '메모지 작성',
  'Add Memo': '메모지 작성',
  'New Flock': '신규 그룹',
  'New Note': '새로 만들기',
  'New Page': '페이지 작성',
  'New Topic': '신규 토픽',
  'Not Found.': '찾을 수 없습니다',
  'Not Owner': '작성자가 아닙니다',
  'Note': '주석',
  'Notebook': '노트',
  'Notebook name': '노트 이름',
  'Notebook saved in cloud as': '노트를 클라우드에 보존했습니다',
  'Notice': '알림',
  'ELLIPAE': '타원',
  'Open': '열기',
  'Overwrite': '덮어쓰기',
  'Page Name': '페이지 이름',
  'Pages': '페이지',
  'Password': '패스워드',
  'Paste': '붙이기',
  'Pause': '정지',
  'Pink Memo': '분홍색 메모지',
  'Play': '재생',
  'Please log in.': '로그인 해주세요',
  'Please save': '저장해 주세요',
  'please wait': '잠시 기다려 주세요',
  'Post Page to Chat': '공동작업 내용을 등록중입니다',
  'Post This Page': '페이지 공개',
  'Presentation': '프레젠테이션',
  'Prev': '앞',
  'Private': '비공개',
  'Project': '프로젝트',
  'Public': '공개',
  'PUBLIC Notebooks': '공개 노트',
  'Radius': '반지름',
  'Randomize Layout': '랜덤 배치',
  'RECTANGLE': '사각형',
  'Redo': '다시 실행',
  'Reference': '출전',
  'Reflesh Chat Nodes': '협업 노드 새로고침',
  'Refresh': '갱신',
  'Registered Site': '등록한 사이트',
  'Release All Fixed': '모든 고정 해제',
  'Relevant Page': '해당 페이지',
  'Reload': '페이지 다시 읽기(갱신)',
  'Reset View': '보기 초기화',
  'Reverse': '역방향',
  'RHOMBUS': '마름모',
  'Role': '역할',
  'Root': '루트',
  'ROUNDED': '둥근 모서리',
  'SAMBUICHI PEs Office': '삼부이치 기술사 사무소',
  'Save': '저장',
  'Save As': '다른 이름으로 저장',
  'Save New': '신규 등록',
  'Save Notebook': '저장',
  'Scatter': '그룹 해제',
  'Scope': '범위',
  'Screenshot': '화면 캡처',
  'Search': '검색',
  'Search Filter': '검색 필터',
  'Search occurrence for the given (sub)string.': '검색문자열을 포함한 컨텐츠를 검색합니다',
  'Search the note for the given (sub)string.': '검색문자열을 포함한 토픽 후보를 필터링합니다',
  'Search topic for the given (sub)string.': '검색문자열을 포함한 토픽을 검색합니다',
  'Select': '선택',
  'Select All': '모두 선택',
  'Select Content': '컨텐츠를 선택',
  'Select Topic': '토픽을 선택',
  'separated with spaces': '공백으로 분할',
  'Setting Options': '옵션 설정',
  'Shape': '모양',
  'Short Cuts': '바로가기',
  'Shortcut Keys': '단축키 표시',
  'Show': '표시',
  'Show All': '모두 보이기',
  'Size': '크기',
  'Solid': '실선',
  'Start': '시작',
  'Static Drawing': '움직임 없이 그리기',
  'Straight': '직선',
  'Subwindow': '실제 컨텐츠',
  'Table': '표',
  'Text': '문자',
  'Text C.': '글자색',
  'Text Color': '문자색',
  'Text File': '텍스트 파일',
  'The notebook was deleted successfully.': '노트를 삭제했습니다',
  'The selected notebook could not be deleted from the cloud service!': '클라우드에서 노트를 삭제할 수 없습니다',
  'The selected notebook could not be loaded from the cloud service!': '노트를 클라우드에서 불러올 수 없습니다',
  'This is the Navigation Window.': '이것은 화면 이동용 창입니다. 여기에는 항상 노트 전체가 표시됩니다.\\n현재 보이는 화면 범위는 붉은선의 틀로 표시되며, 클릭하면 그쪽에 화면 중앙이 배치됩니다.',
  'THUMBNAIL': '미리보기 이미지',
  'Timemachine': '갱신 이력',
  'Toggle': '표시 전환',
  'Toggle Anchor': '고정/유동',
  'Toggle Chat': '시작・종료',
  'Toggle Fix': '고정/유동',
  'Toggle Search': '검색 표시/숨기기',
  'Topic': '토픽',
  'Topic Categoly': '토픽 분류',
  'Topics': '토픽',
  'TRIANGLE': '삼각형',
  'Tree': '트리',
  'Try again after logging in': '로그인한 뒤에 다시 실행해주세요',
  'Tutorial': '튜토리얼',
  'Un/Directed': '유향/무향',
  'undefined': '정의되지 않은',
  'Undirected Bloom': '방향없이 펼치기',
  'Undo': '원래대로 돌리기',
  'Upload': '업로드',
  'Upload File': '파일 업로드',
  'Upload Model ': '업로드',
  'Upload Pdf Annotations': 'PDF주석 업로드',
  'Uploaded': '업로드 완료',
  'URL': 'URL',
  'User ID': '사용자ID',
  'User Name': '사용자 이름',
  'Vertical Axis': '수직축 만들기',
  'Vertical Equal': '세로 정렬',
  'View': '보기',
  'View Notebook XML': '노트 XML 보기',
  'Visible': '표시',
  'Webcat Plus': 'Webcat Plus',
  'White Memo': '흰색 메모',
  'Width': '폭',
  'World Encyclopedia': '세계 백과사전',
  'WuWei & PDF Annotation': 'WuWei 및 PDF 주석',
  'WuWei Manual': 'WuWei 매뉴얼',
  'WuWei Tutorial': 'WuWei 튜토리얼',
  'You are logged in as': '로그인 사용자',
  'You may try to tap SOURCE link to view contents directly.': '내용이 보이지 않으면 SOURCE 링크를 직접 눌러 보세요.',
  'You need to log in before saving. Try to save again after logging in!': '노트를 저장하려면 로그인이 필요합니다. 로그인 후 다시 시도해 주세요',
  'You need to log in to reach your private notebooks': '비공개 노트를 사용하려면 로그인 해주세요',
  'You need to log in to use notebooks': '노트를 사용하려면 로그인 해주세요',
  'Your PRIVATE Notebooks': '비공개 노트',
  'Zoom': '줌',
  'Create a personal content collection and annotate it.': '개인용 콘텐츠 모음을 만들고 주석을 추가합니다.',
  'Visual notes will help you organize your thoughts.': '시각적 노트는 생각을 정리하는 데 도움이 됩니다.'
};
