/**
 * wuwei.nls.TW.js
 * TW translation map
 *
 * Revised against JA baseline on 2026-04-17.
 * WuWei is a free, open-source knowledge modelling tool.
 *
 * Licensed under the MIT License.
 **/
wuwei.nls.TW = {
  'Publish': '發佈',
  'Align': '對齊',
  'Define / Ungroup': '定義/取消群組',
  'Other': '其他',
  'Published': 'Published',
  'Public URL': 'Public URL',
  'Open in new tab': 'Open in new tab',
  'Copy URL': 'Copy URL',
  'Copied': 'Copied',
  'Published note is view-only. Editing, saving, and downloading are disabled.': 'Published note is view-only. Editing, saving, and downloading are disabled.',
  'Disabled': 'Disabled',
  'Download note file': 'Download note file',
  'Upload note file': 'Upload note file',
  'Imported note file': 'Imported note file',
  'Add Page': 'Add Page',
  'Select a page and edit its name.': 'Select a page and edit its name.',
  'Select a page to copy.': 'Select a page to copy.',
  'Select a page to open, edit, copy, or delete.': 'Select a page to open, edit, copy, or delete.',
  'WuWei Home': 'WuWei Home',
  'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.': 'Browse uploaded content and saved webpages, add comments, and start note editing from the selected content.',
  'Search content': 'Search content',
  'Calendar': 'Calendar',
  'Commands': 'Commands',
  'Comment to capture your viewpoint before opening a note.': 'Comment to capture your viewpoint before opening a note.',
  'Content gallery': 'Content gallery',
  'Add to note': 'Add to note',
  'Start date': 'Start date',
  'End date': 'End date',
  'Range target': 'Range target',
  'All content in range': 'All content in range',
  'Selected content in range': 'Selected content in range',
  'Search scope': 'Search scope',
  'Current period': 'Current period',
  'All registered content': 'All registered content',
  'Apply': 'Apply',
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Create a new note from the selected content? Unsaved changes in the current note will be discarded.': 'Create a new note from the selected content? Unsaved changes in the current note will be discarded.',
  'Selected content': 'Selected content',
  'Open note': 'Open note',
  'New note': 'New note',
  'No comment yet': 'No comment yet',
  'Click a card to preview the content and start working.': 'Click a card to preview the content and start working.',
  'No content in selected period': 'No content in selected period',
  'Upload content or choose another date from the calendar.': 'Upload content or choose another date from the calendar.',
  'Selected day': 'Selected day',
  'Month': 'Month',
  'Showing': 'Showing',
  'Date': '日期',
  'Type': '類型',
  'Title': 'Title',
  'Failed to save comment': 'Failed to save comment',
  'Format': 'Format',
  'Saved': 'Saved',
  'This site refused iframe preview.': 'This site refused iframe preview.',
  'Delete this timeline segment?': '要刪除此時間軸區段嗎？',
  'OpenPlayer': '在播放器中開啟',
  'Create timeline axis': '建立時間軸',
  'Axis properties': '軸屬性',
  'Add segment from player': '從播放器新增片段',
  'Segment properties': '片段屬性',
  'Edit segment from player': '從播放器編輯片段',
  'Delete segment': '刪除片段',
  'Info Timeline Segment': '時間軸資訊',
  'SelectAll': '全選',
  'Show All Memo': '顯示全部便箋',
  'Hide All Memo': '隱藏全部便箋',
  'Note Page': '頁面資訊',
  'Select shape': '選擇形狀',
  'Select font size': '選擇字型大小',
  'The iframe preview does not retrieve the current/playback position; instead, it saves the start/end times and uses Open player.': 'iframe 預覽不會擷取目前/播放位置，而是儲存開始/結束時間，並使用 Open Player。',
  'Timeline axis': '時間軸',
  'Media': '媒體',
  'Direction': '方向',
  'horizontal': '水平',
  'vertical': '垂直',
  'Media length': '媒體長度',
  'Default play duration': '預設播放時長',
  'Axis length': '軸長',
  'Axis width': '軸寬',
  'Axis color': '軸色',
  'Timeline segment': '時間軸區段',
  'Video preview': '影片預覽',
  'Set current time to start': '將目前時間設為開始時間',
  'Set current time to end': '將目前時間設為結束時間',
  'Create thumbnail': '建立縮圖',
  'Start time': '開始時間',
  'End time': '結束時間',
  'or': '或',
  'Play duration': '播放時長',
  'info': '資訊',
  'Background Color': '背景色',
  'Length': '長度',
  'Segments': '區段數',
  'Default': '預設',
  'End': '結束',
  'Image': '圖像',
  'Video': '影片',
  'Audio': '音訊',
  'Apply to group': '套用到群組',
  'Media type': '媒體類型',
  'Timeline': '時間軸',
  'Document': '文件',
  'Duration': '時長',
  'Auto': '自動',
  'jump start': '跳到開始位置',
  'jump end': '跳到結束位置',
  'set start here': '將此處設為開始位置',
  'set end here': '將此處設為結束位置',
  'apply': '套用',
  'Define simple group': '定義簡單群組',
  'Define horizontal axis group': '定義水平軸群組',
  'Define vertical axis group': '定義垂直軸群組',
  'Ungroup': '取消群組',
  'Axis': '軸',
  'TimeLine': '时间轴',
  'Create axis group': '建立軸群組',
  'Add time point': '新增時間點',
  'Edit time point': '編輯時間點',
  'Delete time point': '刪除時間點',
  'Text position': '文字位置',
  'CENTER': '中央',
  'TOP': '上',
  'TOP_RIGHT': '右上',
  'RIGHT': '右',
  'BOTTOM_RIGHT': '右下',
  'BOTTOM': '下',
  'BOTTOM_LEFT': '左下',
  'LEFT': '左',
  'TOP_LEFT': '左上',
  'Click the Marker Icon': '單擊標記圖標',
  'HOLLOW-CIRCLE': '空心圈',
  'LINE-ARROW': '線箭頭',
  'HOLLOW-ARROW': '空心箭頭',
  'ARROW': '箭頭',
  'HOLLOW-RHOMBUS': '空心菱形',
  'Chat record': '聊天記錄',
  'Nothing to edit': '沒什麼可編輯的',
  'Archives': '檔案',
  'HORIZONTAL2': '水平',
  'VERTICAL2': '垂直',
  'Web page': '網頁',
  'Total items': '總數',
  'Workbench': '工作區',
  'Source': '来源',
  'Content': '內容',
  '_Content': '內容',
  'Assignment': '任務',
  'Deselect': '取消選擇',
  'Summary': '摘要',
  'Student': '學生',
  'Faculty': '教師',
  'List of Pages': '頁面清單',
  'Loading notebook': '正在加載筆記本',
  'Showing list': '顯示清單',
  'Annotate': '註釋',
  'Clipboard': '剪貼板',
  'Row': '行',
  'Column': '欄',
  'Value': '值',
  'Table Header': '表頭',
  'New Table': '新表',
  'Add Table': '添加表格',
  'Newsletter': '通訊',
  'Questions? Go ahead.': '你有任何問題嗎？請聯繫我們。',
  'Send': '發信息',
  'Message': '信息',
  'Subject': '主題',
  'Email': '電子郵件地址',
  'Contact': '聯絡方式',
  'ERROR LOGIN FAILED': '錯誤：登錄失敗',
  'ERROR NOT LOGGED IN': '錯誤：未登錄',
  'ERROR NOTE DIR NOT DEFINED': '錯誤：筆記本目錄未定義',
  'ERROR RESOURCE DIR NOT DEFINED': '錯誤：資源目錄未定義',
  'ERROR EMPTY KEYWORD': '錯誤：空關鍵字',
  'SUCCESS NOTE REMOVED': '成功：筆記本已刪除',
  'SUCCESS RESOURCE REMOVED': '成功：資源已刪除',
  'SUCCESS RESOURCE UPDATED': '成功：資源已更新',
  'ERROR NOTE NOT REMOVED': '錯誤：未刪除筆記本',
  'ERROR RESOURCE NOT UPDATED': '錯誤：資源未更新',
  'ERROR RESOURCE NOT REMOVED': '錯誤：資源未刪除',
  'Bring forward': '移到前面',
  'Send backward': '移到後面',
  'You are logged in.': '您已登錄。',
  'You are logged out.': '您已註銷。',
  'Do you want to log out?': '您要登出嗎？',
  'Align Top': '顶部对齐',
  'Align Bottom': '底部对齐',
  'Align Right': '右对齐',
  'Align Left': '左对齐',
  'Click to open window': '点击打开窗口',
  'Comment': '說明',
  'Background': '背景',
  'Sourceposition': '起點位置',
  'Targetposition': '終點位置',
  'Info': '資訊',
  'OpenWindow': '在新視窗中開啟',
  'CloseWindow': '关闭窗口',
  'OpenNewTab': '在新分頁中開啟',
  'NORMAL': '一般',
  'HORIZONTAL': '水平',
  'VERTICAL': '垂直',
  'SOLID': '實線',
  'DOTTED': '点線',
  'DASHED': '虛線',
  'LONG-DASHED': '長虛線',
  'Stroke': '線型',
  'erase': '刪除',
  'bloom': '展開',
  'wilt': '摺疊',
  'Bloom': '展開',
  'Wilt': '摺疊',
  'move': '移動',
  'drag': '移動',
  'and': '和',
  '-': '-',
  '+': '+',
  'Abbreviation': '縮寫',
  'About': '關於',
  'addContent': '加入內容',
  'addSimpleContent': '加入內容',
  'Add Content': '加入內容',
  'Add New Topic with Style of This Palette': '添加新的主題與此調色板風格',
  'addTopic': '添加主題',
  'addSimpleTopic': '添加主題',
  'Add Topic': '添加主題',
  'Adjust Size': '调整大小',
  'Align Horizontal': '水平对齐',
  'Align Vertical': '垂直对齐',
  'All': '所有',
  'Amoeba': '變形蟲',
  'Anchor': '錨點',
  'Anchor Mode': '錨點模式',
  'Angle': '角',
  'Anonymous Model': '匿名模型',
  'Anonyous': '匿名',
  'Any unsaved changes will be lost': '任何未保存的更改將丟失',
  'Are you absolutely sure you want to leave': '你真的確認要離開',
  'Are you sure you want to delete the following': '您確定要刪除以下',
  'Are you sure you want to delete this notebook?': '你確定你要刪除這台筆記本？',
  'Are you sure you want to merge': '你確定你要合併',
  'Arrow Head': '箭頭',
  'Associatins': '關聯',
  'Association': '關聯',
  'Association Role': '關聯角色',
  'AUGMENT': '擴充',
  'Blank': '空白',
  'Bloom All Direction': '向所有方向展開',
  'Bloom by Direction': '依方向展開',
  'Blue Memo': '藍色便箋',
  'Cancel': '取消',
  'Close': '關閉',
  'Change': '變化',
  'Change Password': '更改密碼',
  'Chat Mode': '協作模式',
  'CIRCLE': '圓形',
  'Citation': '引文',
  'Class': '類',
  'Clear': '清除',
  'Clear Chat Nodes': '清除聊天節點',
  'Clear Screen': '清除屏幕',
  'Clear Selection': '清除選擇',
  'Clone': '克隆',
  'Cloud mode editing': '雲端編輯模式',
  'Collabolation': '協作',
  'Color': '顏色',
  'COMMIT': '套用',
  'connect': '連接',
  'Resource': '內容',
  'CONTENTS URL': '內容URL',
  'Control Buttons': '控制按钮',
  'Copy': '複製',
  'Copy & Paste': '复制和粘贴',
  'Copyright': '版權',
  'Create & Edit': '創建和編輯',
  'Create Account': '創建賬戶',
  'Create New': '新建',
  'Creator': '创建者',
  'Curve': '曲線',
  'Curve/Line': '曲線/直線',
  'Cut': '剪下',
  'Dashed': '虛線',
  'Date Picker': '日期選取器',
  'defined by': '作者',
  'Delete': '刪除',
  'Deleting information': '正在刪除資訊',
  'Dialog': '對話',
  'Diameter': '直徑',
  'Do you want create new note?': '要建立新筆記嗎？',
  'Dotted': '點',
  'Download': '下載',
  'Downloading information': '下載信息',
  'Drawing Mode': '绘图模式',
  'Dynamic Drawing': '動態繪圖',
  'e-Book List': '電子書列表',
  'e-Books': '電子書',
  'Edge': '關聯線',
  'Edge Shape': '線型',
  'Edit': '編輯',
  'Edit(s) has been made.': '已完成編輯。',
  'Do you want to save edit(s)?': '你想保存编辑吗？',
  'Edit Flock': '編輯群組',
  'Edit Memo': '編輯便箋',
  'Edit Style': '編輯樣式',
  'Editable Mode': '编辑模式',
  'Editing': '編輯',
  'ELLIPSE': '橢圓形',
  'Erase': '刪除',
  'Failed': '失败',
  'File Deleted': '檔案已刪除',
  'File Upload': '文件上傳',
  'Filter': '篩選',
  'Filter Association': '篩選關聯',
  'Filter Topic': '篩選主題',
  'Find': '發現',
  'Fixation': '重新配置',
  'Flock': '群組',
  'Font': '字形',
  'Force All Fixed': '全部固定',
  'Forgot Password?': '忘記密碼？',
  'Free Mode': '自由模式',
  'Get Selected Content Style': '獲取所選內容風格',
  'Get Selected Edge Style': '取得所選線條樣式',
  'Get Style of Selected Item': '獲取所選項目的風格',
  'Go to': '到',
  'Green Memo': '綠色備忘錄',
  'Group': '组',
  'Height': '高度',
  'Hidden': '隐藏',
  'Hide': '隱藏',
  'Hide All': '全部隱藏',
  'Hide Memo': '隱藏備忘錄',
  'Hide Names': '隱藏作者名稱',
  'Horizontal Axis': '建立水平軸',
  'Horizontal Equal': '橫向平等',
  'In case you cannot load iframe contents': '如果無法載入 iframe 內容',
  'Introduction': '介紹',
  'item(s) listed below': '下面列出的項目',
  'Join': '加入群組',
  'Keyword': '關鍵詞',
  'Label': '標籤',
  'Layout Topics': '排列主题',
  'Leave': '移出群組',
  'List': '列表',
  'List of Notebooks': '筆記列表',
  'Load': '加载',
  'Loading information': '加載信息',
  'Local editing mode': '本地編輯模式',
  'Login': '登錄',
  'LOGIN FAILED': '登录失败',
  'Logout': '註銷',
  'maximum size is': '最大尺寸為',
  'members': '群組成員',
  'Memo': '備忘錄',
  'Merge': '合并',
  'Miniature': '縮圖視圖',
  'Miniature Canvas': '縮圖畫布',
  'minimum size is': '最小尺寸是',
  'Model': '模型',
  'More': '更多',
  'Multiple Lines': '多行',
  'Name': '名字',
  'New': '新',
  'New Axis': '新建軸',
  'New Child Topic': '新建子主題',
  'New Citation': '新建引用',
  'New Content': '新建內容',
  'Add Resource': '添加內容',
  'addMemo': '添加備忘錄',
  'addSimpleMemo': '添加備忘錄',
  'Add Memo': '添加備忘錄',
  'New Flock': '新建群組',
  'New Note': '新建',
  'New Page': '新建页面',
  'New Topic': '新主題',
  'Not Found.': '未找到',
  'Not Owner': '非作者',
  'Note': '註記',
  'Notebook': '筆記',
  'Notebook name': '筆記名稱',
  'Notebook saved in cloud as': '筆記本電腦保存在雲中',
  'Notice': '通知',
  'ELLIPAE': '橢圓',
  'Open': '打開',
  'Overwrite': '覆蓋',
  'Page Name': '頁面名稱',
  'Pages': '頁面',
  'Password': '密碼',
  'Paste': '貼',
  'Pause': '暂停',
  'Pink Memo': '粉紅便箋',
  'Play': '播放',
  'Please log in.': '请登录。',
  'Please save': '請妥善保存',
  'please wait': '請稍候',
  'Post Page to Chat': '將頁面發布到聊天',
  'Post This Page': '發布此頁',
  'Presentation': '簡報',
  'Prev': '上一页',
  'Private': '私人',
  'Project': '工程',
  'Public': '公開',
  'PUBLIC Notebooks': '公開筆記',
  'Radius': '半徑',
  'Randomize Layout': '隨機佈局',
  'RECTANGLE': '矩形',
  'Redo': '重做',
  'Reference': '參考',
  'Reflesh Chat Nodes': '重新整理聊天節點',
  'Refresh': '刷新',
  'Registered Site': '註冊網站',
  'Release All Fixed': '全部解除固定',
  'Relevant Page': '相關頁面',
  'Reload': '重新載入',
  'Reset View': '重設檢視',
  'Reverse': '反',
  'RHOMBUS': '菱形',
  'Role': '角色',
  'Root': '根',
  'ROUNDED': '圓角',
  'SAMBUICHI PEs Office': 'SAMBUICHI PE辦公室',
  'Save': '保存',
  'Save As': '保存為',
  'Save New': '保存新',
  'Save Notebook': '保存筆記本',
  'Scatter': '解散群組',
  'Scope': '範圍',
  'Screenshot': '截图',
  'Search': '搜索',
  'Search Filter': '搜尋篩選',
  'Search occurrence for the given (sub)string.': '搜索事件為給定的（子）字符串。',
  'Search the note for the given (sub)string.': '搜索注意對於給定的（子）字符串。',
  'Search topic for the given (sub)string.': '搜索話題，給定（子）字符串。',
  'Select': '選擇',
  'Select All': '全選',
  'Select Content': '選擇內容',
  'Select Topic': '選擇主題',
  'separated with spaces': '用空格隔開',
  'Setting Options': '設置選項',
  'Shape': '形狀',
  'Short Cuts': '捷徑',
  'Shortcut Keys': '快捷鍵',
  'Show': '顯示',
  'Show All': '顯示全部',
  'Size': '尺寸',
  'Solid': '实线',
  'Start': '開始',
  'Static Drawing': '靜態圖',
  'Straight': '直線',
  'Subwindow': '子窗口',
  'Table': '表',
  'Text': '文本',
  'Text C.': '文字顏色',
  'Text Color': '文字顏色',
  'Text File': '文字檔',
  'The notebook was deleted successfully.': '筆記本電腦被成功刪除。',
  'The selected notebook could not be deleted from the cloud service!': '所選擇的筆記本電腦無法從雲服務中刪除！',
  'The selected notebook could not be loaded from the cloud service!': '所選的筆記本無法從雲服務裝！',
  'This is the Navigation Window.': '這是導覽視窗。\n這裡會一直顯示整個筆記本，目前視口會以紅色外框標示。點擊即可移動視口。',
  'THUMBNAIL': '縮略圖',
  'Timemachine': '時間機器',
  'Toggle': '切換',
  'Toggle Anchor': '切換錨',
  'Toggle Chat': '切換聊天',
  'Toggle Fix': '切換修復',
  'Toggle Search': '切換搜尋',
  'Topic': '話題',
  'Topic Categoly': '主題分類',
  'Topics': '主題',
  'TRIANGLE': '三角形',
  'Tree': '树状图',
  'Try again after logging in': '登入後再試',
  'Tutorial': '教程',
  'Un/Directed': '有向/無向',
  'undefined': '未定義',
  'Undirected Bloom': '無向展開',
  'Undo': '復原',
  'Upload': '上傳',
  'Upload File': '上傳文件',
  'Upload Model ': '上傳模式',
  'Upload Pdf Annotations': '上傳PDF註釋',
  'Uploaded': '上傳完成',
  'URL': 'URL',
  'User ID': '使用者 ID',
  'User Name': '用户名',
  'Vertical Axis': '建立垂直軸',
  'Vertical Equal': '垂直對齊',
  'View': '檢視',
  'View Notebook XML': '檢視筆記 XML',
  'Visible': '可見',
  'Webcat Plus': 'Webcat Plus',
  'White Memo': '白色便箋',
  'Width': '寬度',
  'World Encyclopedia': '世界百科全書',
  'WuWei & PDF Annotation': 'WuWei 與 PDF 註釋',
  'WuWei Manual': 'WuWei 手冊',
  'WuWei Tutorial': 'WuWei 教學',
  'You are logged in as': '目前登入使用者',
  'You may try to tap SOURCE link to view contents directly.': '您可以嘗試點擊 SOURCE 連結直接檢視內容。',
  'You need to log in before saving. Try to save again after logging in!': '您需要在保存之前登錄。嘗試登錄後再次保存！',
  'You need to log in to reach your private notebooks': '您需要登錄到您的私人筆記本電腦',
  'You need to log in to use notebooks': '您需要登錄才能使用筆記本電腦',
  'Your PRIVATE Notebooks': '你的私人筆記',
  'Zoom': '放大',
  'Create a personal content collection and annotate it.': '建立個人內容集合並加上註釋。',
  'Visual notes will help you organize your thoughts.': '視覺化筆記可幫助你整理想法。'
};
