#! /bin/sh
# === Initialize shell environment ===================================
set -eux
# -e  Exit immediately if a command exits with a non-zero status.
# -u  Treat unset variables as an error when substituting.
# -v  Print shell input lines as they are read.
# -x  Print commands and their arguments as they are executed.
#export LANG=ja_JP.UTF-8
#export LC_ALL=ja_JP.utf8
export LC_ALL=C
type command >/dev/null 2>&1 && type getconf >/dev/null 2>&1 &&
export PATH="./bin:$(command -p getconf PATH)${PATH+:}${PATH-}"
export UNIX_STD=2003  # to make HP-UX conform to POSIX
Tmp=/tmp/${0##*/}.$$
# === Log ============================================================
exec 2>log/${0##*/}.$$.log
# === Session ========================================================
# --- 1)Read user_id from Cookie ----------------------------------
printf '%s' "${HTTP_COOKIE:-''}" | #tee log/${0##*/}.$$.step1.log |
  sed 's/&/%26/g; s/[;, ]\{1,\}/\&/g; s/^&//; s/&$//' | #tee log/${0##*/}.$$.step2.log |
  cgi-name > $Tmp-cgivars
  user_id=$(nameread wuwei_user_id $Tmp-cgivars)
# --- 2)Response login status from Cookie ----------------------------
if [ -n "$user_id" ]; then
cat <<CONTENT
${user_id}
CONTENT
else
 cat <<CONTENT
  
CONTENT
fi
rm $Tmp-*
rm log/${0##*/}.$$.*
exit 0
